### PR TITLE
fix: add gradients and scrolling to intro pages

### LINKED ISSUE #1377: Text overflow on Intro Screens
The text on the intro screens will overflow if the window is too small and by doing so can push the navigation buttons out of view.

image

**Expected Behavior**

No overflow; scrolling.

### PR DESCRIPTION
**Pull request by dated**
Fixes #1377.

scroll

Also adjusts the position of the Ark logo in the corner.

## What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [x] Refactor
- [ ] Performance
- [ ] Tests
- [ ] Build
- [ ] Documentation
- [ ] Code style update
- [ ] Continuous Integration
- [ ] Other, please describe:

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Does this PR release a new version?

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `develop` branch, _not_ the `master` branch
- [x] All tests are passing
- [ ] New/updated tests are included

If adding a **new feature**, the PR's description includes:

- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

### CODE REVIEW

**Comment by alexbarnsley** [comment]
Looks great! I have one small tweak (which was already there I think):

the `.AppIntro` element has `lg:overflow-y-scroll` - could you change this to `auto` please, since there's always a white bar on the right 🤔 I would do it but got to pop out for an hour (can wait until then otherwise)

**Comment by dated** [comment]
Yea that was already there and I must have missed it. Changed as requested. I also removed the bottom border of the last paragraph on the duty screen.

**Comment by alexbarnsley** [comment]
:myman:

**Comment by dated** [comment]
Codacy ded again.

**Comment by alexbarnsley** [comment]
Deleting comments @dated? :trollface:

**Comment by dated** [comment]
:hide:

**Pull request merged**
