### PR TITLE
fix: add forged to delegate model

### PR DESCRIPTION
**Pull request by dated**
## Proposed changes

https://github.com/ArkEcosystem/desktop-wallet/pull/995 does not include the forged property in the delegate model, causing some errors, `TransactionFormVote` for instance.

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)

## Checklist

- [x] I have read the [CONTRIBUTING](https://docs.ark.io/guidebook/contribution-guidelines/contributing.html) documentation
- [x] Lint and unit tests pass locally with my changes

### CODE REVIEW

**Comment by alexbarnsley** [comment]
I'm not seeing these errors on TransactionFormVote. That component does a separate API request to get forged data for a particular delegate. Can you screenshot where you're getting these errors? 🤔

**Comment by dated** [comment]
image

**Comment by dated** [comment]
It fetches the delegates alright, but does not store the `forged` property, which leads to the `this.client.resource('delegates').forged(delegate.publicKey)` which does not exist for v2.

**Comment by alexbarnsley** [comment]
Thanks for the clarification. Would you mind updating the delegate test data to check for forged values please. Thanks!

**Comment by dated** [comment]
Does this look ok @alexbarnsley?

**Pull request merged**
