### PR TITLE
fix: unconfirmed votes

### LINKED ISSUE #1315: Unvoting does not update the delegate tab banner
When unvoting, the banner on the delegate tab keeps displaying the message "Your Unvote is awaiting confirmation" even when the unvote transaction is well confirmed.

It could be related or a duplicate of https://github.com/ArkEcosystem/desktop-wallet/issues/1097.

**Expected Behavior**

It should change the banner message and display the vote button.

**Your Environment**

- Version used: 2.4.1
- Operating System and version: Ubuntu

### PR DESCRIPTION
**Pull request by alexbarnsley**
- Assumes existing unconfirmed votes without timestamp are expired (pre-2.6.0 vote/unvote)
- Hooks into the votes request that occurs when opening a wallet to clear down unconfirmed votes

Resolves #1315 

## What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Refactor
- [ ] Performance
- [ ] Tests
- [ ] Build
- [ ] Documentation
- [ ] Code style update
- [ ] Continuous Integration
- [ ] Other, please describe:

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Does this PR release a new version?

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `develop` branch, _not_ the `master` branch
- [x] All tests are passing
- [x] New/updated tests are included

If adding a **new feature**, the PR's description includes:

- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

### CODE REVIEW

**Comment by dated** [comment]
> Hooks into the votes request that occurs when opening a wallet to clear down unconfirmed votes

#1442 gets rid of that exact request 🤔

**Comment by alexbarnsley** [comment]
This is a problem 😂

**Comment by dated** [comment]
Hmm i would opt against the hook into the vote request as you could end up with two different states, i.e. the synchroniser hasn't fetched the latest vote yet, but the delegate tab already displays the processed state. Imho the processing should be the responsability of the synchroniser only.

**Comment by alexbarnsley** [comment]
@dated 	I agree. My original plan was the synchroniser but then I decided to go with the votes request since it was there. I'll refactor to use the synchroniser 👌

**Pull request merged**
