### PR TITLE
fix: get children of TransitionGroup when available & word-break of vendorfield

### LINKED ISSUE #1222: Wallets & Contacts right panel
**Platform (please complete the following information):**
 - OS: macOS 10.14.4
 - Desktop Wallet 2.3.2

**Describe the bug**
1. `Smartbridge` text should have `word-break: break-all` or otherwise:
Screenshot 2019-05-04 at 10 10 28

2. When I choose a wallet/contact it's not selected in the right panel:
Screenshot 2019-05-04 at 10 18 14

### PR DESCRIPTION
**Pull request by dated**
## Proposed changes

Fixes and closes #1222 (both issues).

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (improve a current implementation without adding a new feature or fixing a bug)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Build (changes that affect the build system)
- [ ] Docs (documentation only changes)
- [ ] Test (adding missing tests or fixing existing tests)
- [ ] Other... Please describe:

## Checklist

- [x] I have read the [CONTRIBUTING](https://docs.ark.io/guidebook/contribution-guidelines/contributing.html) documentation
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

## Further comments

`collections_filterChildren` would fail to collect the navigation items if they were wrapped in a `TransitionGroup`. That method now checks for such a container and adjusts the `ref` accordingly.

### CODE REVIEW

**Comment by dated** [comment]
Will take a look in the morning!

**Comment by dated** [comment]
@j-a-m-l can you check with the team if this is by design?

```
<style lang="postcss">
.WalletSidebar--expanded .WalletSidebar__wallet .MenuNavigationItem__border {
  @apply .hidden
}
</style>
```

This block has been there for quite a while.

**Comment by j-a-m-l** [comment]
The border should be visible when expanded too

**Comment by alexbarnsley** [comment]
If I remember correctly the border did some weird stuff when expanding. Try removing it @dated and see what happens. If it's okay then can remove it completely

**Comment by dated** [comment]
i'll re-check as soon as i get a chance.

**Comment by dated** [comment]
it looks okay to me @alexbarnsley

**Comment by alexbarnsley** [comment]
Okay great @dated, happy for you to remove it. Maybe the issue it was hiding will represent itself in a few months 😆

**Comment by dated** [comment]
been there, done that #f41baa9 😉

**Comment by alexbarnsley** [comment]
You didn't even wait for confirmation! I should have said the opposite :trollface:

**Comment by alexbarnsley** [comment]
You didn't even wait for confirmation! I should have said the opposite :trollface:

**Pull request merged**
