### PR TITLE
feat: support for tabular layout

### PR DESCRIPTION
**Pull request by dated**
## Proposed changes

Implements https://github.com/ArkEcosystem/desktop-wallet/issues/798.

layout

- [x] add `WalletTable` component
- [x] support sorting by name
- [x] extend for use on contacts page
- [x] add voted delegate
- [x] add loaders
- [x] add `new contact` button/row
- [x] add `loading ledger`

## Types of changes

- [x] New feature (non-breaking change which adds functionality)

## Checklist

- [x] I have read the [CONTRIBUTING](https://docs.ark.io/guidebook/contribution-guidelines/contributing.html) documentation
- [x] Lint and unit tests pass locally with my changes

### CODE REVIEW

**Comment by boldninja** [comment]
@dated can we in list view add a column for who you voting for from each account?

**Comment by dated** [comment]
That should be doable with a "i am voting for.." tooltip/icon. I'll try a few things.

**Comment by boldninja** [comment]
@dated how is this looking? Can this take priority I'd like this in, in the next release we'll do. Will change tier to 1 for motivation.

**Comment by alexbarnsley** [comment]
@dated 	is this still WIP?

**Comment by dated** [comment]
yea, i need to finish the `create contact` button and `loading ledger` 😕

**Comment by alexbarnsley** [comment]
no worries, just wanted to check 👌

**Comment by alexbarnsley** [comment]
@dated 	maybe this would be easy for the "Create" button?:

image

**Comment by dated** [comment]
hmm 😕  i'll try to debug the ledger situation but i don't have mine with me.

**Comment by dated** [comment]
```
this.ledgerWallets = await this.fetchVotedDelegates(this.$store.getters['ledger/wallets'])

this.selectableWallets = [...this.ledgerWallets, ...this.selectableWallets]
```

for starters, this is clearly wrong, as it just keeps on adding to `selectableWallets`.

**Comment by alexbarnsley** [comment]
True 😂 	i briefly looked at that stuff. I did noticed a possible other issue when i looked at the code (after i found the issue). It fetches votes but only for normal wallets, not for the ledger wallets. I didn't properly test though as ledger was already playing up

**Comment by j-a-m-l** [comment]
@dated great work!

Some suggestions:
 - Disable or remove the button to delete Ledger wallets
 - Change the pointer of the "Delete" column since it can't be used for sorting
 - Adapt it to narrow screens, currently it's hard to read because the background is transparent.

**Pull request merged**
