### PR TITLE
fix(plugins): load menu routes correctly

### PR DESCRIPTION
**Pull request by j-a-m-l**
## Proposed changes
The menu items (on the main sidebar) of plugins were not working.

Apart from that, `iframe` wasn't able to load URLs that were protected.

## Types of changes
- [x] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

## Checklist
- [x] I have read the [CONTRIBUTING](https://docs.ark.io/guidebook/contribution-guidelines/contributing.html) documentation
- [x] Lint and unit tests pass locally with my changes

### CODE REVIEW

**Comment by j-a-m-l** [comment]
This PR is almost finished, but it needs https://github.com/ArkEcosystem/desktop-wallet/pull/1191 to add a new permission (`UNPROTECTED_IFRAME`).

**Comment by alexbarnsley** [comment]
@j-a-m-l is this ready or still WIP? if it's ready just waiting on #1191 I'll have to point it to the `next` branch.

**Comment by alexbarnsley** [comment]
I've updated the permissions, it now requires `UNPROTECTED_IFRAME_URLS`. I'm not really sure what this PR fixes though, since i can load Fun's games through an iframe without these changes. What are you deeming as a "protected" URL @j-a-m-l?

**Comment by j-a-m-l** [comment]
@alexbarnsley some pages are protected to avoid being included inside `iframe`s (https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options). As an example: https://github.com/j-a-m-l/ark-desktop-wallet-exchanges

**Comment by j-a-m-l** [comment]
Another plugin that uses `iframe`s: https://github.com/j-a-m-l/ark-desktop-explorer. As the other, it needs to bypass the security.

**Pull request merged**
