### PR TITLE
feat: add sidebar animation

### PR DESCRIPTION
**Pull request by dated**
## Proposed changes

Adds an animation to the sidebar upon expanding or collapsing and fixes the "white border issue" caused by the transition on the bottom border. I deemed the fading out and in necessary since there is no proper way to transition the flex-direction property.

sidebar

## Types of changes

- [x] New feature (non-breaking change which adds functionality)

## Checklist

- [x] I have read the [CONTRIBUTING](https://docs.ark.io/guidebook/contribution-guidelines/contributing.html) documentation
- [x] Lint and unit tests pass locally with my changes

### CODE REVIEW

**Comment by j-a-m-l** [comment]
@dated, could you try fading out / in only the namd and balance, so the identicon is always visible?

**Comment by dated** [comment]
I can give it a go, but i think it will look a bit funky as well since the navigation items are changing in height, hence the identicons will be moving around in two dimensions.

**Comment by dated** [comment]
With the identicons visible it just doesn't look smooth and good. The change of the height and the bottom border makes the transition rather clunky. A positive sideeffect of this approach is also that the transition is only applied to the parent container and not to every single menu Item.

**Comment by j-a-m-l** [comment]
@dated could you upload a GIF of that new animation?could you upload a GIF of the original animation, but faster?

**Comment by dated** [comment]
Faster:
faster

Identicon always visible:
no-identicon

**Comment by alexbarnsley** [comment]
yeh i think it looks better showing the identicons. since the only thing that should fade is anything that changes 🤔

**Comment by dated** [comment]
your call ;)

**Pull request merged**
