### PR TITLE
fix: Change display logic when refreshing addresses

### PR DESCRIPTION
**Pull request by JeremiGendron**
- Display placeholder WalletIdenticons to prevent y-axis motion
 - Create a separate TransitionGroup which remains in place to prevent x-axis motion

Fixes: #944

## Proposed changes
walletnew_reload-ui

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Refactoring (improve a current implementation without adding a new feature or fixing a bug)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Build (changes that affect the build system)
- [ ] Docs (documentation only changes)
- [ ] Test (adding missing tests or fixing existing tests)
- [ ] Other... Please describe:

## Checklist

- [x] I have read the [CONTRIBUTING](https://docs.ark.io/guidebook/contribution-guidelines/contributing.html) documentation
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
<!--

### CODE REVIEW

**Comment by zillionn** [comment]
Can you also make the logo of the not selected addresses more transparent, something like `opacity: .3` and selected with `opacity: 1`?

**Comment by JeremiGendron** [comment]
@zillionn sure thing

**Comment by JeremiGendron** [comment]
walletnew-reload-more

**Comment by alexbarnsley** [comment]
Hi @JeremiGendron, your tests seem to be failing

**Comment by JeremiGendron** [comment]
@alexbarnsley alright, I'll debug that

**Comment by JeremiGendron** [comment]
@alexbarnsley local tests hang, what should I do?

**Comment by JeremiGendron** [comment]
will open a new pull request with similar changes

**Pull request closed without merging**
