### PR TITLE
[WIP] refactor(ui): Change Wallet Import page

### PR DESCRIPTION
**Pull request by JeremiGendron**
## Proposed changes

 - "Choose how to import" Label, followed by:
 - Select either Address or Passphrase (blue-button's)
 - Corresponding address: [text-green (address)] if BIP39
 - (Talk about password encryption @ step 2)
 - Modify step 3 header and Wallet name input label

Ref: #902

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Refactoring (improve a current implementation without adding a new feature or fixing a bug)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Build (changes that affect the build system)
- [ ] Docs (documentation only changes)
- [ ] Test (adding missing tests or fixing existing tests)
- [ ] Other... Please describe:

## Checklist

- [x] I have read the [CONTRIBUTING](https://docs.ark.io/guidebook/contribution-guidelines/contributing.html) documentation
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

## Screenshots

shot1
shot2
shot3
shot4
shot5
shot6
shot7

## Further comments
These are tentative changes, please review.

@doubled1c3 please check out the screen shots and provide feedback.

Other team members as well!

### CODE REVIEW

**Comment by doubled1c3** [comment]
WOW this is amazing, clean intuitive. Massive score :)

**Comment by alexbarnsley** [comment]
@olejegcord can you review the screenshots above please. I know I sent you the above address/passphrase screenshot and you wanted something different

**Comment by doubled1c3** [comment]
That functionality is retained through the greentext upon successful entry of passphrase, so the user can have a quick look to confirm. @alexbarnsley

**Comment by alexbarnsley** [comment]
And the problem there is when you said "quick look". The purpose before was to make sure the entire address the user had matched the passphrase. Just "looking" to compare addresses is prone to user error.

**Comment by michaelthecryptoguy** [comment]
- [ ] "Choose how to import" Label, followed by:
- [ ] Select  either Address or Passphrase (blue-button's)
- [ ] Modify step 3 header and Wallet name input label
- [ ] Corresponding address: [text-green (address)] if BIP39

> That looks excellent

**Comment by michaelthecryptoguy** [comment]
> * [x]  "Choose how to import" Label, followed by:
> * [x]  Select  either Address or Passphrase (blue-button's)
> * [x]  Modify step 3 header and Wallet name input label
> * [x]  Corresponding address: [text-green (address)] if BIP39
> 
> > That looks **Excellent** `Very Clean!!`

Can you see check marks here, or are they only on my screen?

**Comment by zillionn** [comment]
Why you have to choose anything to import a wallet? Can we just have both fields visible all the time and a text `and/or` between them?
Wallet address: ______________
and/or
Passphrase: _______________

**Comment by JeremiGendron** [comment]
Glad to hear some feedback, will listen for further instructions.

**Comment by doubled1c3** [comment]
@JeremiGendron @alexbarnsley @zillionn 

I went off the starting method of "this/that/show/hide" and proposed improvements to that. We can have both address and passphrase visible and remove the show/hide switches, but it would be a bit more work to make the text fields smart enough to handle the cases:

A. Enter only address, next button becomes clickable, but passphrase can still be entered too
B. Enter only passphrase, if address blank, autocomplete address field, if address not blank, run validation check and display error if problem

This method is good too.

I just feel the switches are kind of wonky and removing the switches and making the text fields smarter, or having two easy button choices, gives a clear workflow of what they are doing and why they are doing it

I settled on the buttons because it does show the user there are two ways to import, which are different from each other, and the user will understand what each of them means. I have spoken to users who imported watch-only and thought for some reason they could control their funds. So for that reason the two method buttons combined with the explainer text (@JeremiGendron can you add explainer text according to mockup https://user-images.githubusercontent.com/32085788/50551291-2c715100-0c33-11e9-9360-5f6cc4393119.png) is pretty nice.

Alex regarding your comment re: validation, the two always visible fields with no switches handles that validation case a bit better, but I do believe the current solution of displaying the greentext is sufficient for confirmation the address is familiar to them...

**Comment by alexbarnsley** [comment]
@doubled1c3 who is "them"? If we're to make it as safe as possible for first time users, surely we should be doing everything we can to make sure they don't lose any tokens? Users who have literally just started out in the crypto/blockchain space are nervous and we should give them a categorical "this passphrase matches this address". It's not like banks, which you seem to be comparing with, it's a 34 character address with both letters and numbers that they have to make sure is correct. I don't want people importing wallets with an address which they believe is correct for their wallet, which isn't.

**Comment by doubled1c3** [comment]
@alexbarnsley Naturally, I agree.

We modify based on dropping the switches, making both boxes always visible, but making them smarter.

a. We drop the Address/Passphrase buttons
b. We drop the Only/Only switches
c. We make both fields always visible
d. If user enters only address, next button become clickable, for watch-only mode
e. If user enters only passphrase, address field autopopulates on successful BIP39 entry
f. If user enters address and then passphrase, it performs a validation against the address the user entered, on successful passphrase entry.
g. We drop the "Corresponding Address:" greentext. It would now be handled through autocompleting the address field.
h. Change main intro text on this step: 

image

becomes

Import wallet
"Enter an address to import in watch only mode, or enter the passphrase to perform a full import and control your funds. Optionally, you may enter both address and passphrase to perform a validation check before importing."

At this point the user can import via address, wallet, both and perform a legit verification, and there are no more switches or buttons to deal with, clean

maybe @JeremiGendron can throw the changes in and we can check out the result from there

**Comment by olejegcord** [comment]
Thank you for telling us your idea, we appreciate it and will take some things into implementation. In this moment we have already updated the UI and UX on the "Wallet Import" page, it will be available in the new updates in the fast time. :)

**Comment by zillionn** [comment]
Use Passphrase (if you own the wallet and want to set encrypted password for faster sending):
`______________________________________________________`
or Address (if you don't own the wallet and want to import it in Watch Only mode):
`______________________________________________________`

If passphrase - populate the `Address` field.

@doubled1c3 It should always populate the address even if not BIP39 passphrase, because some users use custom passphrases. However, checking if the passphrase is BIP39 is a must have, maybe a yellow text below the passphrase field:
`The passphrase you've entered is not a valid BIP39! Please double check your passphrase if you're not using a custom passphrase.`

**Pull request closed without merging**
