### PR TITLE
refactor: chart buttons hover background color

### PR DESCRIPTION
**Pull request by dated**
## Proposed changes

There is currently no visual feedback when hovering over the chart header buttons.

nohover -> hover

## Types of changes

- [x] Refactoring (improve a current implementation without adding a new feature or fixing a bug)

## Checklist

- [x] I have read the [CONTRIBUTING](https://docs.ark.io/guidebook/contribution-guidelines/contributing.html) documentation
- [x] Lint and unit tests pass locally with my changes

### CODE REVIEW

**Comment by j-a-m-l** [comment]
In your example, `Day` should change too

**Comment by dated** [comment]
Since `Day` is the currently active button that is not necessary imho.

**Comment by j-a-m-l** [comment]
Since there is only 1 active button, maybe it's better changing the opacity on hover on active and inactive buttons, instead of using the same style.

**Comment by dated** [comment]
Doesn't look so good 😕

transitions

The style of the PR is in alignment with how the buttons are handled on the explorer.

**Comment by j-a-m-l** [comment]
If you don't differentiate the active button and the hover, that's confusing.

About looking good, I'd say that it's almost the same. Push those changes, and I'll review and approve them.

**Pull request merged**
