### PR TITLE
fix: pasting or writing numbers with colon (",") on the send transfer inputs

### PR DESCRIPTION
**Pull request by j-a-m-l**
## Proposed changes
This PR fixes, at least, 1 of the problems of https://github.com/ArkEcosystem/desktop-wallet/issues/999

## Types of changes
- [x] Bugfix (non-breaking change which fixes an issue)
- [x] Test (adding missing tests or fixing existing tests)

## Checklist
- [x] I have read the [CONTRIBUTING](https://docs.ark.io/guidebook/contribution-guidelines/contributing.html) documentation
- [x] Lint and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by dated** [comment]
```
const numeric = value ? parseFloat(value.toString().replace(',', '.')) : 0
```

This will fail for inputs that have the following format: `1,234.56`

Something like the following should do the trick (untested)

```
const numeric = value ? parseFloat(sanitizeInput(value)) : 0
```
with
```
sanitizeInput (value) {
  const parts = value.toString().replace(',', '.').split('.')
  return parts.slice(0,-1).join('') + '.' + parts.slice(-1)
}
```

`toString()` can probably be omitted.

**Comment by j-a-m-l** [comment]
Yes, @dated, I was aware of that (and that we would need to support `1.233.233,12`), but I'm waiting to get more feedback from https://github.com/ArkEcosystem/desktop-wallet/issues/999, to include more cases if necessary, such as `100 000.00` or `100_000.00`.

**Comment by zillionn** [comment]
```js
Number(
  amount.toString()
   .split(' ').join('')
   .split(',').join('')
   .split('_').join('')
)
```

**Comment by dated** [comment]
That would result in `123,45` to become `12345`. The above replace call with the regex should cover all cases outlined by @j-a-m-l.

**Comment by zillionn** [comment]
I see but I don't understand which program is generating `123.45` as `123,45`? There is no such string/number... Comma is used for thousands only.

**Comment by dated** [comment]
This ist highly dependent of localisation.

**Comment by boldninja** [comment]
Some use commas for thousands (a lot of EU) and some use dots (US/UK).
For example:
In Slovenia: 100.200,30
In English: 100,200.30

**Comment by zillionn** [comment]
If that's the case, then I guess you need to use something like this throughout the whole app:
https://github.com/globalizejs/globalize

You have `Application Language` in the profile settings and you should follow that setting. Even remove the `Time Format` setting.

**Comment by j-a-m-l** [comment]
It looks like it has more support for some things than https://github.com/kazupon/vue-i18n, but, since we aren't having troubles with localization yet, I'd stick with the current library to not make a very big refactor without any big reason.

About following the language setting, keep in mind that people could copy and paste amounts from sites on other languages.
In some countries, people are used to both time formats and it's just a matter of preference.

**Comment by zillionn** [comment]
Didn't look at the code, but if I put `1,234` how much is that `1234` or `1.234`?

**Comment by j-a-m-l** [comment]
It depends on the locale: if you locale uses "." as decimal separator, it would assume 1.234, if not, it would use 1234

**Comment by zillionn** [comment]
Oh, you're checking the locale, nice!

**Pull request merged**
