### PR TITLE
fix: allow selecting the balance on the wallet page heading

### PR DESCRIPTION
**Pull request by j-a-m-l**
## Proposed changes
Resolves https://github.com/ArkEcosystem/desktop-wallet/issues/993

## Types of changes
- [x] Bugfix (non-breaking change which fixes an issue)
- [x] Test (adding missing tests or fixing existing tests)

## Checklist
- [x] I have read the [CONTRIBUTING](https://docs.ark.io/guidebook/contribution-guidelines/contributing.html) documentation
- [x] Lint and unit tests pass locally with my changes

### CODE REVIEW

**Comment by alexbarnsley** [comment]
Maybe it's worth going a little further than this. Using the `user-select` CSS property on the whole identicon, the name and address (since that can be copied with the button).

**Comment by j-a-m-l** [comment]
@alexbarnsley what do you mean? The text is already selectable. Do you refer to change it on other parts of the application?

**Comment by alexbarnsley** [comment]
Sorry I was clear, preventing the selection on the whole identicon, the name and address. `user-select: none`. There's probably a tailwind class for it

**Comment by dated** [comment]
there is, `select-none`

**Comment by j-a-m-l** [comment]
OK, now I know the reason, but I think that it's better to be practical in that sense and allow users to select the name and address, just in case they want to use it for whatever reason.

I've changed the badges of the identicons and the placeholder of the contacts page.

**Pull request merged**
