### PR TITLE
fix: saving of invalid profile name on leave

### PR DESCRIPTION
**Pull request by kalgoop**
When you leave profile edition page and click save option when leaving, this saves profile even if the profile name is duplicate
## Proposed changes

Save changes if profile name isn't a duplicate

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)

## Checklist

- [x] I have read the [CONTRIBUTING](https://docs.ark.io/guidebook/contribution-guidelines/contributing.html) documentation
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by kalgoop** [comment]
@alexbarnsley Showing an error when fails to update profile name

**Comment by j-a-m-l** [comment]
@alexbarnsley this PR has been updated, does it meet your expectations?

**Comment by alexbarnsley** [comment]
I'll take a look after the next release. Thanks for the ping @j-a-m-l

**Comment by alexbarnsley** [comment]
I've made some changes @kalgoop - will merge once tests pass

**Pull request merged**
