### PR TITLE
fix: don't close custom peer modal when clicking inside

### PR DESCRIPTION
**Pull request by j-a-m-l**
## Proposed changes
After opening the modal to add a custom peer, it's impossible to use it, because when clicking inside it, it's automatically closed.

## Types of changes
- [x] Bugfix (non-breaking change which fixes an issue)
- [x] Refactoring (improve a current implementation without adding a new feature or fixing a bug)

## Checklist
- [x] I have read the [CONTRIBUTING](https://docs.ark.io/guidebook/contribution-guidelines/contributing.html) documentation
- [x] Lint and unit tests pass locally with my changes

### CODE REVIEW

**Comment by alexbarnsley** [comment]
I think I tested this a few days ago but I've slept since. Just to confirm, this is when clicking the overlay to close the modal, it should keep the peer settings menu open in the sidebar? @j-a-m-l

**Comment by j-a-m-l** [comment]
@alexbarnsley I've updated the PR description.

**Comment by alexbarnsley** [comment]
🤔 i didn't experience that. I will re-test, probably after the next release

**Comment by dated** [comment]
This is more of a problem with the click-outside directive imho, as the problem is present elsewhere as well (`settings -> reset data` for instance). The current behaviour also stops a menu from closing after re-clicking on the button which opens it.

**Comment by dated** [comment]
Well, the easy fix for the reset data modal is an extra condition to emitting the close signal:

```
if (this.outsideClick && !this.isResetDataModalOpen) {
  this.$emit('close')
}
```

I added that in #1146; the second issue mentioned is still standing.

**Pull request merged**
