### PR TITLE
feat: add validation to VerifyModal

### PR DESCRIPTION
**Pull request by kalgoop**
## Proposed changes

Check if signature length is 140
Check if json has message, publicKey, signature of appropriate length

## Types of changes

- [x] New feature (non-breaking change which adds functionality)

## Checklist

- [x] I have read the [CONTRIBUTING](https://docs.ark.io/guidebook/contribution-guidelines/contributing.html) documentation
- [x] Lint and unit tests pass locally with my changes

### CODE REVIEW

**Comment by alexbarnsley** [comment]
@kalgoop are these accompanied by some user feedback? If not, people won't know why they can't send their transaction

**Comment by kalgoop** [comment]
@alexbarnsley placeholder shows '64 character signature. Right?
I think that is enough

**Comment by faustbrian** [comment]
There should be specific user feedback so the user knows what exactly the issue is rather then a generic error message.

**Comment by j-a-m-l** [comment]
@kalgoop could you display the user feedback based on the problem (the message is empty, the public key is incorrect, etc.)?

**Comment by alexbarnsley** [comment]
Closing as no response for over 2 weeks.

**Pull request closed without merging**
