### PR TITLE
feat: add votes page

### PR DESCRIPTION
**Pull request by brenopolanski**
## Summary

Screenshot from 2020-06-30 14-53-46

## Checklist

- [ ] Documentation _(if necessary)_
- [x] Tests _(if necessary)_
- [x] Ready to be merged

### CODE REVIEW

**Comment by samharperpittam** [comment]
Quick note on this PR @brenopolanski 

The table column titles 'My Address / Balance / Delegate / Rank etc' should be 14px. Think they are set to 12 currently.

**Comment by faustbrian** [comment]
@brenopolanski conflicts

**Comment by faustbrian** [comment]
@brenopolanski conflicts

**Comment by brenopolanski** [comment]
> Quick note on this PR @brenopolanski
> 
> The table column titles 'My Address / Balance / Delegate / Rank etc' should be 14px. Think they are set to 12 currently.

@samharperpittam @faustbrian I'll send another PR to fix titles in the tables.

**Pull request merged**
