### PR TITLE
bug: fix multiple profile creation on multiple clicks

### PR DESCRIPTION
**Pull request by kalgoop**
On the profile creation page, I have noticed that when in the end you have to press 'Done'. If you press that button multiple times quickly, you'll get multiple profiles created with the same name.
This problem is more visible on slow networks as it gives more time for multiple clicks.

A user may press Done multiple times if the profile doesn't load instantly.
## Proposed changes

in the create function, profile name is revalidated if its unique

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)

## Checklist

- [x] I have read the [CONTRIBUTING](https://docs.ark.io/guidebook/contribution-guidelines/contributing.html) documentation
- [x] Lint and unit tests pass locally with my changes

### CODE REVIEW

**Comment by JeremiGendron** [comment]
@kalgoop I found the bug, I'll submit a PR to your branch now.

**Comment by kalgoop** [comment]
@JeremiGendron nice catch ! I think this would fix the issue. I'll test this tomorrow morning and rollback my commit if your commit is enough to ensure non duplicate profile names

**Comment by dated** [comment]
Why not disable the button once clicked? `ReloadButton` for reference.

**Comment by JeremiGendron** [comment]
```js
        <button
          v-if="isNextVisible || isNextEnabled"
          :disabled="!isNextEnabled || isLastItemClicked"
          class="MenuStepItem__footer__next-button blue-button"
          @click="emitNext(isLastItem)"
        >
```
@dated already in place

**Comment by JeremiGendron** [comment]
@kalgoop could work better (event listeners should be triggered after setting isLastItemClicked, not before):
```js
    emitNext (isLastItem) {
      if (isLastItem) {
        this.isLastItemClicked = true
        this.$emit('next')
      }
      if (!this.lastItemClicked) {
        this.$emit('next')
      }
    }
```

**Comment by kalgoop** [comment]
Everything seems to be fine. I tried really hard to click the Done button multiple times but failed. :smile:

**Pull request merged**
