### PR TITLE
misc: add translation for Portuguese (Brasil)

### PR DESCRIPTION
**Pull request by Pedro-Souza**
## Proposed changes
Adding translate for pt-br
## Types of changes
- [x] Other... Please describe:

## Checklist

- [x] I have read the [CONTRIBUTING](https://docs.ark.io/guidebook/contribution-guidelines/contributing.html) documentation
- [x] Lint and unit tests pass locally with my changes

### CODE REVIEW

**Comment by j-a-m-l** [comment]
Thanks for your PR. Currently we are studying several options to handle translations, so we might take some time before including your work.

**Comment by Pedro-Souza** [comment]
@j-a-m-l Done!

**Comment by alexbarnsley** [comment]
@j-a-m-l are you happy with this?

**Comment by j-a-m-l** [comment]
We need the new intro screens, those that allow choosing the language first. I could implement that after this release, @alexbarnsley.

**Comment by j-a-m-l** [comment]
@Pedro-Souza We have changed the introductory screens, and now users can select the language at the beginning. Since we have included new features, some texts have been added, so you probably wouldn't need to make big changes to your translation.

Related to that, we have added a tool to check what transactions are missing. You can see the instructions on the `develop` branch: https://github.com/ArkEcosystem/desktop-wallet#translations

If you have any doubt, please contact me. Your translation would be released on the new version :tada:

**Comment by j-a-m-l** [comment]
@Pedro-Souza I'm going to close this PR due inactivity. If you are interested on finishing it, you could re-open it or create a new one.

**Pull request closed without merging**
