### PR TITLE
fix: Provide chart tooltip when hovering on x-axis

### LINKED ISSUE #951: Show the price and time tooltip when mousing over the MarketChart
**Is your feature request related to a problem? Please describe.**
It is not convenient to have to track the LineChart's line to get more precise pricing info.

**Describe the solution you'd like**
The tooltip that appears when on the line to be displayed relative to the mouse's position on the x-axis

**Describe alternatives you've considered**
I've tried to implement a vertical line mapping to the time as well, but was unsuccessful with vue-chartjs plugins.

**Additional context**
Current:
marketchartbefore

### PR DESCRIPTION
**Pull request by JeremiGendron**
## Proposed changes

Provide a tooltip relative to the mouse's current position on the x-axis with the addition of two vue chartjs tooltip options.

After:
marketchartupgrade

Before: 
marketchartbefore

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Refactoring (improve a current implementation without adding a new feature or fixing a bug)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Build (changes that affect the build system)
- [ ] Docs (documentation only changes)
- [ ] Test (adding missing tests or fixing existing tests)
- [ ] Other... Please describe:

## Checklist

- [x] I have read the [CONTRIBUTING](https://docs.ark.io/guidebook/contribution-guidelines/contributing.html) documentation
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

## Further comments
Closes #951

### CODE REVIEW

**Comment by JeremiGendron** [comment]
Let's see

**Comment by JeremiGendron** [comment]
@luciorubeens hasn't triggered yet, right?

**Comment by luciorubeens** [comment]
@JeremiGendron Ye, I think you should close this PR and open another.

**Comment by alexbarnsley** [comment]
@luciorubeens 	possible issue with codecov. You've not got one on yours #960

**Comment by alexbarnsley** [comment]
oh wait, i misunderstood 🤔

**Comment by alexbarnsley** [comment]
It is weird. Please open a new PR from the same branch @JeremiGendron

**Pull request closed without merging**
