### PR TITLE
fix: Various style improvements

### PR DESCRIPTION
**Pull request by JeremiGendron**
## Proposed changes

related to #645 
Fixes: 
- Remove whitespace at top of WalletSidebar.vue (pt-0)
- Create/import wallet buttons misaligned (align: center && .pt-6 .pb-6)

The other commit is an issue with the left sidebar where the icon didnt clear other active menu when clicked (fixed with an older commit to develop, was working against another branch).
## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Refactoring (improve a current implementation without adding a new feature or fixing a bug)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Build (changes that affect the build system)
- [ ] Docs (documentation only changes)
- [ ] Test (adding missing tests or fixing existing tests)
- [ ] Other... Please describe:

## Checklist

- [x] I have read the [CONTRIBUTING](https://docs.ark.io/guidebook/contribution-guidelines/contributing.html) documentation
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by JeremiGendron** [comment]
Fixes: 
- self-stretched / flex ButtonLoader (now inline-flex, fits all its uses)
- properly centred Create/Import wallet buttons
- @click.native redirect('dashboard') for the AppSidemenu (unselects when clicking on logo)
- whitespace at the top of wallet preview removed with pt-0
- moved "Network Overview" to "Network" rather than "Settings" and merged the pop-aside network stats with the "Connect your peer" and "Network Overview" Buttons (will add horizontal rule or similar to differentiate between stats and other menus)

**Comment by dated** [comment]
image

The reload button needs the `self-strech` here, as it is smaller than the other buttons without.

**Comment by JeremiGendron** [comment]
@dated I'll fix that now

**Comment by alexbarnsley** [comment]
I will have to check with Oleg the designer regarding moving the Network Overview option, and also the removing of them as separate buttons. They were part of the design he created. I suspect Network Overview was underneath settings because it is just that, network settings. While the Peer (cloud icon) is simply for managing which peer I'm connected to.

I've passed it on to Oleg so will await feedback, thanks.

**Comment by alexbarnsley** [comment]
Oleg replied just as I commented. He would like it to look like the following, but he's happy with the sections they are in:

image

**Comment by JeremiGendron** [comment]
Thanks Alex! Touching it up right now.

**Comment by alexbarnsley** [comment]
Hi @JeremiGendron, did you finish the changes? I wasn't sure. Also, there are now conflicts you will need to take a look at. Thanks

**Comment by JeremiGendron** [comment]
I'll update these first thing in the morning. For now these are all the
changes.

**Comment by JeremiGendron** [comment]
@alexbarnsley all done.

**Comment by alexbarnsley** [comment]
Hi @JeremiGendron - All looking good. Oleg just had 1 request, to add the line between "Custom Peer" and "Network Overview" which you can see in the example:

image

If you could add this i'll get it merged. thanks

**Comment by alexbarnsley** [comment]
@JeremiGendron 	i pushed a change to get that added for you so we can get this merged

**Pull request merged**
