### PR TITLE
test: plugin manager unit tests

### PR DESCRIPTION
**Pull request by dated**
## Summary

Adds unit tests for plugin manager related parts, mainly the plugin store module.

image

## Checklist

- [ ] Documentation _(if necessary)_
- [x] Tests _(if necessary)_
- [x] Ready to be merged

### CODE REVIEW

**Comment by alexbarnsley** [comment]
👀

**Comment by dated** [comment]
@alexbarnsley 👀

**Comment by alexbarnsley** [comment]
It's a good start :trollface:

**Comment by dated** [comment]
:danstop:

**Comment by boldninja** [comment]
:noah:

**Pull request merged**
