### PR TITLE
feat: implement address navigation directly in the wallet

### LINKED ISSUE #811: Feature re-enable
**Is your feature request related to a problem? Please describe.**

Feature Reenable - I miss being able to view any other wallet address in the desktop wallet by clicking on someone's address, versus it always having to open in the explorer now
I think the reason Arkio done this was to relieve a conflict of interest with the wallet and the block explorer.

### PR DESCRIPTION
**Pull request by luciorubeens**
## Proposed changes

Implement the ability to open any address directly in the wallet.

Fixes #811

## Types of changes

- [x] New feature (non-breaking change which adds functionality)

### CODE REVIEW

**Comment by j-a-m-l** [comment]
:clap:

**Comment by luciorubeens** [comment]
@j-a-m-l Did you run my last commit? I set up the wallet as a contact, so these tabs should not be displayed for contacts. https://github.com/ArkEcosystem/desktop-wallet/pull/793/commits/fdb9296acd780700eb470b9275601cbb33de9116#diff-a4c65940a180037fae3ddcac8fcd6677R26

**Comment by j-a-m-l** [comment]
Yes, I've used the latest change on this branch (https://github.com/ArkEcosystem/desktop-wallet/pull/793/commits/382b0d3b24c50aea8db34b17d6b808fbfd6bae43). In contacts I don't see those empty tabs.

**Comment by luciorubeens** [comment]
@j-a-m-l Ok, it looks like the `MenuTab` component does not re-render when the slot is updated, then I called manually.

**Comment by j-a-m-l** [comment]
@luciorubeens There is another problem that is not on the current develop branch: for some reason, hovering at addresses is making the tooltip blink _furiously_.

**Pull request merged**
