### PR TITLE
[WIP] feat: different display for transaction sent to self

### PR DESCRIPTION
**Pull request by dated**
## Proposed changes

Implements #928.

Also fixes:

 - watch only wallets were not flagged as such

image

The screenshot shows four of the possible scenarios.

1) tx sent from other wallet to own wallet
2) tx sent from own wallet to the same wallet
3) tx sent from own wallet to other own wallet
4) tx sent from own wallet to other wallet

## Types of changes

- [x] New feature (non-breaking change which adds functionality)

## Checklist

- [x] I have read the [CONTRIBUTING](https://docs.ark.io/guidebook/contribution-guidelines/contributing.html) documentation
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by zillionn** [comment]
IMO you should completely remove the +/- signs on last transactions page, because I have wallets that are not mine - watch only. Like the explorer's homepage https://explorer.ark.io/
Maybe use only `±` when sender and recipient is the same.

**Comment by dated** [comment]
I've changed it as such that the new prefix and icon get applied only to transactions where sender === recipient or to transactions where both wallets are owned and have not been imported as watch only. The watch only flag was never set however during the wallet import, so you'd need to reimport those wallets.

**Comment by boldninja** [comment]
I agree with @dated here is also for visually impaired (color) so if they can see somehow real representation (in - out - not yet confirmed) without the need to hover over to see the actual confirmations etc... would be good as well.

**Comment by dated** [comment]
I did only introduce the yellow dot for neither exclusively incoming (green) or outgoing (red) ;)

Yellow was a poor choice, i agree with that.

**Pull request closed without merging**
