### PR TITLE
feat: create `SelectAddress` component

### PR DESCRIPTION
**Pull request by goga-m**
## Summary
Depends on https://github.com/ArkEcosystem/desktop-wallet/pull/2447

Add `SelectAddress` as form element that opens `SearchContact` modal and selects an address of a profile.
* Accepts `disabled` `isInvalid` state from props or `formContext`
* `isVerified` prop to show verified status icon
* emits `onChange` event when the address is selected and set

Usage:
```jsx
<SelectAddress
	isInvalid
	isVerified
	disabled
	contacts={contacts}
	ref={ref}
	address="bP6T9GQ3kqP6T9GQ3kqP6T9GQ3kqTTTP6T9GQ3kqT"
	onChange={(address) => console.log(address)}
/>


```

Preview:

2020-07-13-180534_812x647_scrot

 

## Checklist

- [ ] Documentation _(if necessary)_
- [x] Tests _(if necessary)_
- [x] Ready to be merged

### CODE REVIEW

**Comment by faustbrian** [comment]
@goga-m build fails

**Comment by goga-m** [comment]
@faustbrian checking it now

**Comment by goga-m** [comment]
@faustbrian re-run again locally after the last merge and built successfully. Thanks :+1:

**Comment by goga-m** [comment]
Now the tests :-). Let me check again

**Comment by goga-m** [comment]
All look good after the latest resolution

**Pull request merged**
