### PR TITLE
feat: allow plugins to connect to best peer

### PR DESCRIPTION
**Pull request by dated**
## Summary

Plugins might need to find a peer that meets certain criteria. For example a peer that doesn't use estimates in their database lookups. Currently, the only way to achieve that is by prompting the user to refresh the peer himself.

This PR exposes the `connectToBest` action from the `peer` store module as `walletApi.peers.connectToBest()` (needs the `PEER_ALL` permission) so that plugins are able to find a peer that fits the plugins needs.

## Checklist

- [ ] Documentation _(if necessary)_
- [x] Tests _(if necessary)_
- [x] Ready to be merged

### CODE REVIEW

**Comment by davimello28** [comment]
Is it safe? It feels weird to me that a plugin can control what I'm connected to. It seems a break in the hierarchy of the application, much like a browser selecting which network I should connect to (despite the fact that a peer can be random).

**Comment by dated** [comment]
I do agree actually. At the very least it should not be possible if the current peer is a custom peer.

**Comment by alexbarnsley** [comment]
@dated maybe this can be reworked so that a modal is shown for the user to confirm changing to best peer 🤔 that way it can't be used in the background because the user will be notified. Not too sure how to go about where to put that modal without looking into it more closely though

**Comment by dated** [comment]
Closing this as I agree with the modal-based approach.

**Pull request closed without merging**
