### PR TITLE
refactor: wallet transactions & delegate table sorting

### PR DESCRIPTION
**Pull request by dated**
## Proposed changes

Imho sorting should not trigger a potential change of the dataset, but only manipulate the order of the data already present. The current implementation fetches the delegates in the `onSortChange` method.

## Types of changes

- [x] Refactoring (improve a current implementation without adding a new feature or fixing a bug)

## Checklist

- [x] I have read the [CONTRIBUTING](https://docs.ark.io/guidebook/contribution-guidelines/contributing.html) documentation
- [x] Lint and unit tests pass locally with my changes

### CODE REVIEW

**Comment by dated** [comment]
Should probably extended to `WalletTransactions.vue` as well.

**Comment by j-a-m-l** [comment]
I'm not sure about this. IIRC, we passed from sorting the rows locally on the initial implementations to doing it remotely.

About the pointer, please, include it on other PR.

**Comment by dated** [comment]
added to #735

**Comment by dated** [comment]
all it does is refetching the delegates before sorting them, which delays the action unnecessarily.

```
const { delegates, totalCount } = await this.$client.fetchDelegates({
  page: this.queryParams.page,
  limit: this.queryParams.limit
})
this.delegates = this.__sortDelegates(delegates)
```

**Comment by alexbarnsley** [comment]
There a few issues with this:

1 - Going to page 2 and sorting resets the page to 1, but shows page 2's sorted data
2 - If i sort date ascending on page one it sorts locally. When i then go to page 2, it shows page 2 of my very early transactions, because sorting is also done on the API
3 - Assuming you removed the API sorting, your change means I may never be able to see my very first transactions if I have a lot

I agree with @j-a-m-l that this should be done remotely, as I would expect to see my first transaction on page 1 if i sorted locally.

**Comment by dated** [comment]
Yes, i hadn't looked into the transaction fetching properly. This PR was originally intended only for the delegates table, the changes to the transactions were added later and are obviously wrong.

The delegate table has no remote sorting however, should that be added? If not I'd still say that the re-fetching of the delegates is superfluos.

**Pull request closed without merging**
