### PR TITLE
feat: pending balance tooltip with unconfirmed transactions

### PR DESCRIPTION
**Pull request by dated**
~This adds a tooltip to the balance in the wallet header showing the count and sum of unconfirmed transactions.~

Changed to show the remaining balance including the unconfirmed transactions instead.

image

## What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Refactor
- [ ] Performance
- [ ] Tests
- [ ] Build
- [ ] Documentation
- [ ] Code style update
- [ ] Continuous Integration
- [ ] Other, please describe:

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Does this PR release a new version?

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `develop` branch, _not_ the `master` branch
- [x] All tests are passing
- [ ] New/updated tests are included

If adding a **new feature**, the PR's description includes:

- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

### CODE REVIEW

**Comment by alessiodf** [comment]
`over` doesn't seem the right word to use in the tooltip imo. Maybe something like `with a total of` (or just `totalling`) or maybe `accounting for` would be better.

**Comment by alessiodf** [comment]
You're welcome.

**Comment by ItsANameToo** [comment]
Works, but 2 remarks:

1) can you add a `pointer: cursor` when the tooltip is available and you hover over the amount? 
2) I hover over it as I know it exists, but I doubt a regular user will find this feature. So maybe we need a way to indicate that the amount can be hovered over when there is a pending transaction? 🤔 thoughts @alexbarnsley ?

**Comment by alexbarnsley** [comment]
I agree, but not sure how you would highlight that it can be hovered over 🤔

**Comment by ItsANameToo** [comment]
We could add a dotted underline to the amount or something? 🤔

**Comment by ItsANameToo** [comment]
Only when the tooltip becomes available, so it would attract attention to it as it has "changed"

**Comment by luciorubeens** [comment]
Maybe an icon next to the amount

**Comment by alexbarnsley** [comment]
Maybe ask Oleg for an icon to highlight that there's a tooltip, something we can use (almost) anywhere

**Comment by faustbrian** [comment]
@alexbarnsley @dated did Oleg provide an icon or was that ditched in favour of the pointer cursor and can be merged?

**Comment by dated** [comment]
I'm kinda waiting on further instructions :shrug:

**Comment by faustbrian** [comment]
@alexbarnsley what's needed for @dated to complete this PR?

**Comment by alexbarnsley** [comment]
We can leave the icon for now

**Pull request merged**
