### PR TITLE
feat: add `<ArkLogo>` component

### PR DESCRIPTION
**Pull request by brenopolanski**
## Checklist

- [ ] Documentation _(if necessary)_
- [ ] Tests _(if necessary)_
- [ ] Ready to be merged

### CODE REVIEW

**Comment by clucasalcantara** [comment]
Hello hello :3 since ark logo will be just an image isn’t better to create a more generic image component instead of a exclusive component just for the logo? 🤔

**Comment by brenopolanski** [comment]
Hey @clucasalcantara  i'm thinking about the future.

We'll package all the components for the NPM (coming soon). Then we can update this component to work with other variants of the ARK logo (e.g: https://ark.io/mediakit) and other apps can use it ;)

**Comment by faustbrian** [comment]
> Hey @clucasalcantara i'm thinking about the future.
> 
> We'll package all the components for the NPM (coming soon). Then we can update this component to work with other variants of the ARK logo (e.g: [ark.io/mediakit](https://ark.io/mediakit)) and other apps can use it 😉

All the components will be tailored to our applications to avoid them being to generic and having to make them work for other peoples scenarios. These packages that will share front-end and back-end code between our projects are intended only for our products, not to support the UI/UX Development of third-party products.

If third-parties want to copy our UI/UX then they should at least put in the effort of doing the manual labour and not asking us to make compromises in our work because once we go down the path of making our UI/UX generic enough for other people to re-use we end up in a situation where we can't introduce changes because other people rely on specific styles and behaviours.

**Comment by brenopolanski** [comment]
I'll close this PR in favor of a generic component for images

**Pull request closed without merging**
