### PR TITLE
refactor: apply new designs in `SelectNetwork`

### PR DESCRIPTION
**Pull request by goga-m**
2021-03-04-153043_953x738_scrot

## Checklist

-   [x] My changes look good in both light AND dark mode
-   [x] The change is not hardcoded to a single network, but has multi-asset in mind
-   [x] I checked my changes for obvious issues, debug statements and commented code
-   [ ] Documentation _(if necessary)_
-   [x] Tests _(if necessary)_
-   [x] Ready to be merged

### CODE REVIEW

**Comment by faustbrian** [comment]
Task linked: [CU-egzb77 [Misc] network selection adjustments](https://app.clickup.com/t/egzb77)

**Comment by samharperpittam** [comment]
@goga-m  - Looks like the Public Network & Dev network translations are broken

image

**Review by samharperpittam — CHANGES_REQUESTED** [review]
See comment above

**Comment by goga-m** [comment]
@samharperpittam patched the fix. Thanks

**Review by samharperpittam — APPROVED** [review]

**Pull request merged**
