### PR TITLE
[on hold] refactor: remote sorting of delegate table

### PR DESCRIPTION
**Pull request by dated**
## Proposed changes

Adds remote sorting to the delegates table. This PR depends on arkecosystem/core#1731 and will be tested once possible.

## Types of changes

- [x] Refactoring (improve a current implementation without adding a new feature or fixing a bug)

## Checklist

- [x] I have read the [CONTRIBUTING](https://docs.ark.io/guidebook/contribution-guidelines/contributing.html) documentation
- [x] Lint and unit tests pass locally with my changes

### CODE REVIEW

**Comment by luciorubeens** [comment]
@dated Can you check this now? Since your PR was merged and released in core.

**Comment by dated** [comment]
i can test against _devnet_ later to confirm it works. that PR will land in mainnet with the typescript migration, so merging this will have to wait til then in any case.

**Comment by dated** [comment]
This needs one more change on the API side, already discussed with @faustbrian.

**Comment by dated** [comment]
Works fine with `username` and `rank`. The PR for `approval` and `productivity` support has been submitted.

**Pull request closed without merging**
