### PR TITLE
test: fix registration warnings

### PR DESCRIPTION
**Pull request by alexbarnsley**
## Checklist

- [ ] Documentation _(if necessary)_
- [ ] Tests _(if necessary)_
- [ ] Ready to be merged

### CODE REVIEW

**Comment by alexbarnsley** [comment]
@faustbrian seems to fix the warnings. It's weird, it seems to have been caused by the asFragment method

**Comment by faustbrian** [comment]
@alexbarnsley conflicts

**Comment by faustbrian** [comment]
@alexbarnsley syntax errors in tests

**Comment by alexbarnsley** [comment]
Yeh will take a look properly in a bit. I quick fixed the conflicts in GH while I finished something else

**Pull request merged**
