### PR TITLE
chore(deps): update dependencies to their latest versions

### PR DESCRIPTION
**Pull request by faustbrian**
Update all dependencies to their latest versions, excluding `tailwind` and `vue-good-table` because of known issues.

_Includes linting fixes required by the new eslint version._

## What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Refactor
- [ ] Performance
- [ ] Tests
- [x] Build
- [ ] Documentation
- [ ] Code style update
- [ ] Continuous Integration
- [ ] Other, please describe:

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Does this PR release a new version?

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `develop` branch, _not_ the `master` branch
- [x] All tests are passing
- [ ] New/updated tests are included

If adding a **new feature**, the PR's description includes:

- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

### CODE REVIEW

**Comment by alexbarnsley** [comment]
Tailwind wasn't updated 🤔 I checked because it would cause breaking changes as per #1278

**Comment by alexbarnsley** [comment]
Ignore me, i thought you wrote `including`, not `excluding`

**Comment by alexbarnsley** [comment]
@faustbrian conflicts and a failing test

**Comment by faustbrian** [comment]
Will have a look on tuesday.

**Comment by faustbrian** [comment]
@alexbarnsley

**Comment by dated** [comment]
@alexbarnsley can you check if the wallet hangs with `vue-good-table` 2.18.0 as it did with 2.17.x? it runs fine when added to the development branch afaik.

**Comment by faustbrian** [comment]
Closing this as we now have the @renovate-bot for updating dependencies.

**Pull request closed without merging**
