### PR TITLE
refactor: upgrade to TailwindCSS 1.0

### PR DESCRIPTION
**Pull request by sebastiangseijo**
A summary of what changes this PR introduces and why they were made.

## What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Refactor
- [ ] Performance
- [ ] Tests
- [ ] Build
- [ ] Documentation
- [x] Code style update
- [ ] Continuous Integration
- [ ] Other, please describe:

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Does this PR release a new version?

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [ ] It's submitted to the `develop` branch, _not_ the `master` branch
- [ ] All tests are passing
- [ ] New/updated tests are included

If adding a **new feature**, the PR's description includes:

- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

### CODE REVIEW

**Comment by sebastiangseijo** [comment]
Hi,

I have done all the corresponding changes from the tailwind documentation update guide:
https://tailwindcss.com/docs/upgrading-to-v1/

However, there are some font-style things that are not correct with the newer tailwind version, I have run all tests and merged my repo with develop.

When you run the application [In my case, mac os], there is a field which is not aligned correctly, I would like to hear what I can do to solve this but I don't want to start modifying things that are not of this issue

**Comment by alexbarnsley** [comment]
Looks good! I have a few points documented below (@luciorubeens 	could you also test please)

Too much padding at the top of close buttons... sometimes 🤔 
image
image

Wrapping on profiles (they're too thin)
image

Alert padding
image

The whole page has a black border and window is scrollable
image

Too big/cannot scroll avatars or backgrounds in add/edit profile section
image
image

The wallet options menu is broken
image

Loading colours have changed
image

Buttons in wallet header are bigger and have more margin/padding
Before
image
After
image

**Comment by faustbrian** [comment]
@sebastiangseijo Are you still working on this or what's the status?

**Comment by alexbarnsley** [comment]
Marked as stale. If unresponsive, it will get closed.

**Comment by alexbarnsley** [comment]
dam bot :fthat:

**Comment by sebastiangseijo** [comment]
Hi guys, thought it was approved, working on this today and tomorrow.

**Comment by faustbrian** [comment]
@sebastiangseijo what's the status? Would be good to know how far you progressed as there is some work upcoming that will be easier if this PR is first merged.

**Comment by sebastiangseijo** [comment]
I couldn't fix the remaining issues of this PR

**Comment by alexbarnsley** [comment]
Okay, thanks for letting us know. We will probably re-do this to see if we can fix the issues as we migrate, instead of going through and patching new issues/regressions.

**Pull request closed without merging**
