### PR TITLE
Bugfix : Validation after after regenerating 2nd passphrase

### PR DESCRIPTION
**Pull request by kalgoop**
While registering for 2nd passphrase.

Follow these steps to reproduce the bug:
-If you generate a 2nd passphrase
-Then tap next
-Then verify the passphrase (by entering 3,6,9 th words)
-Tap Back
-Generate a new 2nd passphrase
-Tap next
-You will be able to continue without entering correct passphrase

## Proposed changes

This has been fixed by using the rest function from the generateNewPassphrase function.

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)

## Checklist

- [x] I have read the [CONTRIBUTING](https://docs.ark.io/guidebook/contribution-guidelines/contributing.html) documentation
- [x] Lint and unit tests pass locally with my changes

### CODE REVIEW

**Comment by kalgoop** [comment]
@j-a-m-l by generate a new 2nd passphrase,  I mean by clicking on that button (looks like refresh). If you aren't still able to reproduce it, I'll add a video

**Comment by j-a-m-l** [comment]
Yes, that's how I did.

**Comment by kalgoop** [comment]
@alexbarnsley
In 6th step you are entering wrong passphrase ?

**Comment by kalgoop** [comment]
@alexbarnsley after the PR, https://www.youtube.com/watch?v=a9d9N8TIl90
@j-a-m-l you can see the steps in above video. Without the PR, Next button is enabled (in the end)

**Pull request merged**
