### PR TITLE
feat: Draggable wallet sorting

### PR DESCRIPTION
**Pull request by JeremiGendron**
## Proposed changes

related to #636 

Change: every WalletSidebar MenuNavigationItem (wallet) can be dragged to another wallet's position and push them down. Layout is persisted by setting state.wallets[wallet.profileId] to a spliced-with copy of itself containing the new order.

This requires the addition of vuedraggable, a very simple to use library stored in `@/components/utils/Draggable`.

This probably affects touch screens as well.

I'm open to working further on this.

I have considered including an index prop with each wallet, though it would've taken me much longer to get that done properly. I have also considered giving a `disabled: .ledgerWallet` class/option to DraggableJS; this would ensure that the ledger wallet(s?) can't be dragged or dropped on.

THe changes are still untested with a ledger wallet. 

I wasn't sure whether it would be acceptable to call `refreshLedgerWallets()` after reordering occurs, there's no good way to do that in one frame (refreshing sends the ledger wallet to the top).

I think currently it allows to reorder the ledger wallet like any other wallet, though on a new session it's automatically refreshed and brought to the top.

Let me know if this PR makes sense, also: how to handle ledger wallets.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Refactoring (improve a current implementation without adding a new feature or fixing a bug)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Build (changes that affect the build system)
- [ ] Docs (documentation only changes)
- [ ] Test (adding missing tests or fixing existing tests)
- [ ] Other... Please describe:

## Checklist

- [x] I have read the [CONTRIBUTING](https://docs.ark.io/guidebook/contribution-guidelines/contributing.html) documentation
- [] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by alexbarnsley** [comment]
Hi, you have a conflict

I think this overall looks good. Would it be possible to add dragging to the main wallet list? Possibly have one of those dotted blocks you click-hold and then drag using that? Not sure if you can as i've never used vuedraggable. The only bug I noticed was that the wallet identicons changed to a square when dragging, but before releasing. Could you possibly fix that for me please. Thanks!

**Comment by alexbarnsley** [comment]
@JeremiGendron 	let me know when you've finished with your changes and i'll have another test

**Comment by JeremiGendron** [comment]
ping @alexbarnsley

**Comment by alexbarnsley** [comment]
sorry @JeremiGendron, there are some conflicts 😞

**Comment by JeremiGendron** [comment]
Yes, I will resolve them and push again.

**Pull request closed without merging**
