### PR TITLE
fix: show the right balance on wallets not owned by the user or contacts

### PR DESCRIPTION
**Pull request by j-a-m-l**
## Proposed changes
Resolves https://github.com/ArkEcosystem/desktop-wallet/issues/1057

## Types of changes
- [x] Bugfix (non-breaking change which fixes an issue)

## Checklist
- [x] I have read the [CONTRIBUTING](https://docs.ark.io/guidebook/contribution-guidelines/contributing.html) documentation
- [x] Lint and unit tests pass locally with my changes

### CODE REVIEW

**Comment by dated** [comment]
when switching from wallet A (owned) with `balance > 0` to wallet B (owned) with `balance === 0` it will still show the balance from wallet A i believe.

**Comment by j-a-m-l** [comment]
Thanks @dated

**Comment by dated** [comment]
🤔 does this work? `wallet_fromRoute` still returns a 'fresh' wallet with no balance, doesn't it?

```
const freshWallet = () => {
  return WalletModel.deserialize({
    address,
    name: '',
    profileId: '',
    isContact: true,
    isWatchOnly: true
  })
}

return this.$store.getters['wallet/byAddress'](address) || freshWallet()
```

**Comment by j-a-m-l** [comment]
@dated what advantages do you think that has the `freshWallet` approach? I'm not sure about setting default values for some attributes, such as `isContact`, etc.

**Comment by dated** [comment]
I meant that `this.currentWallet` will always fall back to the freshWallet object above, since the looked up wallet is not stored.

**Comment by j-a-m-l** [comment]
Yes, but I'm not sure if it's better transitioning from wallet A, to wallet Fresh, to wallet B, instead of A -> B. It could provoke fast UI changes or things like that. I mean, the current fix tries to not provoke side effects, but maybe I could review your idea later to see how it works on every scenario.

**Comment by dated** [comment]
The snippet above is from the actual implementation of `wallet_fromRoute`. I was merely wondering If this PR actually fixes the problem at hand, which is showing the balance of unowned (or unknown through contacts) wallets.

**Comment by j-a-m-l** [comment]
I didn't find any failing case :man_shrugging:, but you are free to try it; maybe I have missed something.

**Comment by luciorubeens** [comment]
Fixed via #1094

**Pull request closed without merging**
