### PR TITLE
feat(plugins): implement ability to overwrite elements with slots

### PR DESCRIPTION
**Pull request by luciorubeens**
## Proposed changes

Register a global component to be used by plugins

## Types of changes

- [x] New feature (non-breaking change which adds functionality)

### CODE REVIEW

**Comment by alexbarnsley** [comment]
@luciorubeens is there a particular plugin you have available that can be used to test this with? Thanks

**Comment by luciorubeens** [comment]
@alexbarnsley Here you go: https://github.com/luciorubeens/ark-desktop-custom-chain. Currently have to access the route to load, but can be improved next.

**Comment by alexbarnsley** [comment]
Looks great! How do you think it could work without having to be on a specific page? e.g. I enable this plugin and the footer is always "My custom chain" while on that profile?

Also, I'm getting a warning about portal-target not being PascalCase:

image

**Comment by luciorubeens** [comment]
Yeh, I thought about loading at startup, does not it look good?

`PascalCase` problem fixed.

**Comment by j-a-m-l** [comment]
@luciorubeens I just tried it, and it works, but, maybe it would be better to rename the `PortalTarget` to "plugin-footer", but continue exposing it as "footer", so the code of the wallet differentiates clearly which portals are intended to be used internally and which others are there for plugins.

**Comment by luciorubeens** [comment]
Agreed. Done! @j-a-m-l

**Comment by alexbarnsley** [comment]
@j-a-m-l yes, it needed PluginWrapper to point to the updated portal name. I've made the change if you want to test it.

**Pull request merged**
