### PR TITLE
refactor: use consistent `Send` buttons in transaction forms

### PR DESCRIPTION
**Pull request by goga-m**
## Checklist
Depends on https://github.com/ArkEcosystem/desktop-wallet/pull/3257
-   [x] Show loading state when submitting transaction form
-   [x] Apply same send-button ux in `SendIpfs`, `SendRegistration`, `SendVote`, `SendTransfer` `SendDelegateResignation`

-   [x] My changes look good in both light AND dark mode
-   [x] The change is not hardcoded to a single network, but has multi-asset in mind
-   [x] I checked my changes for obvious issues, debug statements and commented code
-   [ ] Documentation _(if necessary)_
-   [x] Tests _(if necessary)_
-   [x] Ready to be merged

### CODE REVIEW

**Comment by faustbrian** [comment]
Task linked: [CU-aerryw Normalise Sending a Transaction with the spinner](https://app.clickup.com/t/aerryw)

**Comment by samharperpittam** [comment]
@goga-m  - Is it possible to change the IPFS Send button to match the others? 

It currently states ' [icon]Sign & Continue' but other transaction forms have ' [icon] Sign'

image

I haven't seen any other forms with 'Sign & Continue' but I'll keep looking.

**Review by samharperpittam — CHANGES_REQUESTED** [review]
See comment

**Comment by goga-m** [comment]
Yeah about the text wasn't sure if it was intentional so I left it as is. Missed the spacing. Patching now, thanks for checking it @samharperpittam

**Comment by goga-m** [comment]
@samharperpittam patched

**Review by samharperpittam — APPROVED** [review]

**Pull request merged**
