### PR TITLE
Fix/tabindex ci test

### PR DESCRIPTION
**Pull request by JeremiGendron**
#933

### CODE REVIEW

**Comment by JeremiGendron** [comment]
I've:

 1. Cloned the repo from arkecosystem/desktop-wallet
 2. Rename origin -> && Add remote origin jeremigendron/desktop-wallet
 3. Fetch origin && Push develop to origin
 4. Cherry-pick origin's branch (individual commits) relevant to this PR
 5. Push to new origin branch
 6. Open PR on new branch

Still nothing..

**Comment by JeremiGendron** [comment]
image

**Comment by JeremiGendron** [comment]
There's also no diff between my .circleci and upstream/develop's

**Comment by alexbarnsley** [comment]
The only thing i can think of is to remove your repo and re-fork. You risk losing the changes you've made though. Possibly pull down all your branches locally, re-fork, then push the branches back.

**Comment by JeremiGendron** [comment]
Yeah doing so now

**Pull request closed without merging**
