### PR TITLE
refactor: add plugin updates confirmation modal

### PR DESCRIPTION
**Pull request by luciorubeens**
## Summary

https://app.clickup.com/t/3k3991

## Checklist

-   [ ] My changes look good in both light AND dark mode
-   [ ] The change is not hardcoded to a single network, but has multi-asset in mind
-   [ ] I checked my changes for obvious issues, debug statements and commented code
-   [ ] Documentation _(if necessary)_
-   [ ] Tests _(if necessary)_
-   [ ] Ready to be merged

### CODE REVIEW

**Review by ItsANameToo — CHANGES_REQUESTED** [review]
@luciorubeens does this PR rely on https://github.com/ArkEcosystem/desktop-wallet/pull/3427 ? I don't get the modal when I click on a single plugin to update even though it has the warning about the desktop version being too low in the list 🤔 

image

**Comment by luciorubeens** [comment]
@ItsANameToo The update option is now disabled in the dropdown menu.

**Review by ItsANameToo — CHANGES_REQUESTED** [review]
image
looks like the avatar for the plugins is a bit too large to fit the modal 🤔

**Review by samharperpittam — CHANGES_REQUESTED** [review]
@luciorubeens 

Can we also add this message to the plugins with viewed in card view. Currently it only shows within List view.

image

**Comment by luciorubeens** [comment]
@samharperpittam fixed

**Review by samharperpittam — APPROVED** [review]

**Review by ItsANameToo — APPROVED** [review]

**Pull request merged**
