### PR TITLE
fix: how the tooltip is hidden when scrolling

### PR DESCRIPTION
**Pull request by j-a-m-l**
## Proposed changes
Solves https://github.com/ArkEcosystem/desktop-wallet/issues/767

@dated @JeremiGendron would you mind to try this branch?

## Types of changes
- [x] Bugfix (non-breaking change which fixes an issue)

## Checklist
- [x] I have read the [CONTRIBUTING](https://docs.ark.io/guidebook/contribution-guidelines/contributing.html) documentation
- [x] Lint and unit tests pass locally with my changes

### CODE REVIEW

**Comment by JeremiGendron** [comment]
Booting up

**Comment by JeremiGendron** [comment]
rev1
not working

**Comment by j-a-m-l** [comment]
I don't know if this can be really solved... :man_shrugging:

**Comment by dated** [comment]
Maybe by attaching the tooltip to the table. I'll give it a try tomorrow if not resolved by then.

**Comment by j-a-m-l** [comment]
I tried that (`container: ".TransactionTable"`) and I didn't perceived any change. Anyway, I'd appreciate your collaboration @dated.

**Comment by JeremiGendron** [comment]
Possibly use some other library or creating an overlay div on the table
with py-[tooltip-size].

**Comment by dated** [comment]
i'm testing something right now, should be ready in a couple of minutes

**Comment by j-a-m-l** [comment]
Close, because https://github.com/Akryum/v-tooltip/issues/145 is probably the best place to solve it.

**Pull request closed without merging**
