### PR TITLE
feat: implement auto updater

### PR DESCRIPTION
**Pull request by luciorubeens**
## Proposed changes

Implement the auto updater for Windows and MacOS.

- [x] Handle the `update-available` event.
- [x] Handle the `download-progress` event.
- [x] Handle the `update-downloaded` event.
- [x] Upload the required files to the latest release.

## Types of changes

- [x] New feature (non-breaking change which adds functionality)
- [x] Refactoring (improve a current implementation without adding a new feature or fixing a bug)
- [x] Build (changes that affect the build system)

### CODE REVIEW

**Comment by ItsANameToo** [comment]
Status on this 🤔

**Comment by luciorubeens** [comment]
I was waiting for Oleg's design, I'll check with him.

**Comment by alexbarnsley** [comment]
@olejegcord 🤔

**Comment by alexbarnsley** [comment]
@faustbrian is there a way to ignore entire files/folders for codeclimate?

**Comment by luciorubeens** [comment]
Yeh, dev mode installation does not work. Agreed, I'll fix the footer spacing.

**Pull request merged**
