### PR TITLE
docs: add instructions to install via package managers

### PR DESCRIPTION
**Pull request by luciorubeens**
## Types of changes

- [x] Docs (documentation only changes)

### CODE REVIEW

**Comment by ItsANameToo** [comment]
homebrew :mindblown:

**Comment by j-a-m-l** [comment]
@luciorubeens I'm not familiar with homebrew, but the package doesn't appear on https://formulae.brew.sh/formula/.

The Arch version does appear.

**Comment by ItsANameToo** [comment]
It's available tho:

```
 brew search ark-desktop
==> Casks
ark-desktop-wallet
```

**Comment by zillionn** [comment]
@ItsANameToo That is a GitHub cask.

**Comment by ItsANameToo** [comment]
@zillionn yes? :P

**Comment by zillionn** [comment]
That was actually for @j-a-m-l. You can't find it on https://formulae.brew.sh/formula/ but `brew` searches on GitHub for macOS apps.

**Comment by j-a-m-l** [comment]
@zillionn thanks for the info

**Pull request merged**
