### PR TITLE
fix: enable the translation of empty transaction table message

### PR DESCRIPTION
**Pull request by danielstc**
## Proposed changes

If another language is chosen, the 

> No transactions have been found. The latest transactions will be displayed here.

messages translations are not working.

Adds:
`:no-data-message="$t('TABLE.NO_TRANSACTIONS')"` 

in:
1. `src/renderer/components/Dashboard/DashboardTransactions.vue` 

2. `src/renderer/components/Transaction/TransactionTable.vue`

## Types of changes

- [x ] Bugfix (non-breaking change which fixes an issue)

## Checklist

- [x] I have read the [CONTRIBUTING](https://docs.ark.io/guidebook/contribution-guidelines/contributing.html) documentation

### CODE REVIEW

**Comment by luciorubeens** [comment]
Hey @danielstc, sounds good! but 3 days ago there was an [interruption in CircleCI](https://status.circleci.com) and your test did not run

**Comment by danielstc** [comment]
Hi @luciorubeens. Ok. I have to do something? Let me know.

**Comment by luciorubeens** [comment]
@danielstc Yes, try sending an empty commit or check your CircleCI account to re-run

**Comment by dated** [comment]
Another way is by force-pushing a new commit (don't do `git add .` if there are other un-committed changes on your branch):

```
git reset HEAD~
git add .
git commit -m "fix: enables the translation of missing messages"
git push -f origin fix/display-no-transactions-message
```

**Comment by luciorubeens** [comment]
Fixed by updating the branch, thanks!

**Comment by danielstc** [comment]
@luciorubeens perfect! Thank you.

**Pull request merged**
