### PR TITLE
fix: add margin only when confirmations truthy & chores

### PR DESCRIPTION
**Pull request by dated**
## Proposed changes

Additional changes to #1129 which can either be merged into that branch or I'll rebase this PR if #1129 gets merged first.

This PR adds a clipboard button for the block id and adds a condition to the clipboard button of the transaction id, so there is no right margin when the explorer link is missing.

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [x] Other... Please describe: chores

## Checklist

- [x] I have read the [CONTRIBUTING](https://docs.ark.io/guidebook/contribution-guidelines/contributing.html) documentation
- [x] Lint and unit tests pass locally with my changes

### CODE REVIEW

**Comment by j-a-m-l** [comment]
Thanks @dated. I'll wait until the other PR is merged to review this one.

**Comment by dated** [comment]
:+1: I'll rebase this when it's time to do so

**Comment by dated** [comment]
@alexbarnsley can you reopen? It was probably closed because the base got deleted.

**Comment by alexbarnsley** [comment]
Oops! Didn't realise it was linked to a different branch

**Comment by j-a-m-l** [comment]
@danielstc could you clean the unrelated changes / commits?

**Comment by dated** [comment]
Rebasing must have messed that up. I'll fix it tonight.

**Comment by dated** [comment]
All done @j-a-m-l

**Comment by dated** [comment]
Sorry, that slipped by while adding the changes. Fixed now.

**Comment by dated** [comment]
image

Works here 🤔

**Comment by j-a-m-l** [comment]
@dated yesterday my branch wasn't correctly updated. I've tried again and it worked. Thanks.

**Pull request merged**
