### PR TITLE
refactor: implement new fee input

### PR DESCRIPTION
**Pull request by dated**
## Summary

https://app.clickup.com/t/dk19zd
https://app.clickup.com/t/dk1aax
https://app.clickup.com/t/dmzcfz
https://app.clickup.com/t/e13d7u
https://app.clickup.com/t/e13dbh

## Checklist

-   [ ] My changes look good in both light AND dark mode
-   [ ] The change is not hardcoded to a single network, but has multi-asset in mind
-   [ ] I checked my changes for obvious issues, debug statements and commented code
-   [ ] Documentation _(if necessary)_
-   [x] Tests _(if necessary)_
-   [x] Ready to be merged

### CODE REVIEW

**Comment by faustbrian** [comment]
Task linked: [CU-dk19zd [fee] rename min/avg/max to slow/avg/fast](https://app.clickup.com/t/dk19zd)

**Comment by faustbrian** [comment]
Task linked: [CU-dmzcfz [fee] implement new fee input design](https://app.clickup.com/t/dmzcfz)

**Comment by faustbrian** [comment]
Task linked: [CU-dk1aax [fee] disable min/avg/max buttons when they cannot be used](https://app.clickup.com/t/dk1aax)

**Comment by faustbrian** [comment]
Task linked: [CU-e13d7u [fee] show fee options only if network supports dynamic fees](https://app.clickup.com/t/e13d7u)

**Comment by faustbrian** [comment]
Task linked: [CU-e13dbh [fee] fetch fees on network change not on wallet change](https://app.clickup.com/t/e13dbh)

**Review by samharperpittam — APPROVED** [review]

**Pull request merged**
