### PR TITLE
fix: plugin table sorting

### PR DESCRIPTION
**Pull request by dated**
## Proposed changes

Fixes the sorting on the plugin table which was overwriting the sorting of the contacts.

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (improve a current implementation without adding a new feature or fixing a bug)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Build (changes that affect the build system)
- [ ] Docs (documentation only changes)
- [ ] Test (adding missing tests or fixing existing tests)
- [ ] Other... Please describe:

## Checklist

- [x] I have read the [CONTRIBUTING](https://docs.ark.io/guidebook/contribution-guidelines/contributing.html) documentation
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by dated** [comment]
It should work now as expected @j-a-m-l

**Comment by j-a-m-l** [comment]
It looks like the status column doesn't work.

**Comment by dated** [comment]
It looks like when the plugins are first loaded, the `isEnabled` property is not set, which caused the sorting to fail. I fixed this on the sorting-side only now.

**Comment by dated** [comment]
I'm getting some strange errors, will wrap this up tonight.

**Pull request merged**
