### PR TITLE
feat: different style for names provided by the network & ui fixes

### PR DESCRIPTION
**Pull request by dated**
## Proposed changes

image

When a wallet or contact has no name assigned, but a name can be retrieved from the network, it is now shown in a different color and a tooltip shows up when hovering the name.

Also fixes some of the issues described in #997:

- merge wallets and ledger wallets in wallet list and wallet sidebar, so that there are no duplicates in the list
- respect numerical order when ordering by wallet name (e.g. 1 -> 2 -> 10 instead of 1 -> 10 -> 2)
- add ledger badge to wallet sidebar

And also:

- makes the whole wallet/contact card clickable instead of only the identicon and name
## Types of changes

- [x] New feature (non-breaking change which adds functionality)

## Checklist

- [x] I have read the [CONTRIBUTING](https://docs.ark.io/guidebook/contribution-guidelines/contributing.html) documentation
- [x] Lint and unit tests pass locally with my changes

### CODE REVIEW

**Comment by dated** [comment]
ready for review, yea :)

**Comment by dated** [comment]
Will be fixed by EOD!

**Comment by j-a-m-l** [comment]
Now, everything looks OK, except
 - Making the whole card clickable: I like it, but selecting the balance or name implies clicking accidentally on it, so I wouldn't include this change. What do you think @alexbarnsley @luciorubeens?
 - The create contact card now is misaligned

**Comment by dated** [comment]
I fixed the create contact card, making it clickable as a whole as well.

**Comment by j-a-m-l** [comment]
@dated On mouse over the links should be underlined.

**Comment by dated** [comment]
Only when hovering the name like before or when hovering the whole card (this felt a bit off, hence i didn't add the text-decoration)?

**Comment by j-a-m-l** [comment]
At least when hovering the names.

When hovering the whole card would be another clue that clicking on it could be used to navigate to the wallet/contact, although I'm not completely sure if it would be the best decision aesthetically and for UX.

**Comment by dated** [comment]
Has this been decided on yet?

**Comment by j-a-m-l** [comment]
@alexbarnsley @luciorubeens what's you opinion about https://github.com/ArkEcosystem/desktop-wallet/pull/991#issuecomment-456052224 ?

**Comment by dated** [comment]
I added/changed the following:

- removed click event on card name and balance, so they can be highlighted and copied
- added ledger badge on the wallet cards
- if sidebar is slim
  - added ledger tooltip
  - made ledger badge square

**Pull request merged**
