### PR TITLE
deps: update vue-good-table

### PR DESCRIPTION
**Pull request by dated**
## Summary

Updates `vue-good-table` to `2.18.0` and fixes the table components along with it, stopping the wallet from freezing.

This PR also:

- fixes sorting by voted delegate in the wallets table
- fixes sorting in the transactions table

## Checklist

- [ ] Documentation _(if necessary)_
- [x] Tests _(if necessary)_
- [x] Ready to be merged

### CODE REVIEW

**Comment by dated** [comment]
```
FAIL __tests__/unit/pages/Profile/ProfileAll.spec.js
  ● pages > ProfileAll › totalBalances › should return the sum of balances per network, using their symbols, sorted by quantity descently

    expect(received).toEqual(expected) // deep equality

    - Expected
    + Received

      Array [
    -   "m 500.150909",
    -   "d 0.5201",
    -   "o 0.1219",
    +   "m 500.00",
    +   "d 1.00",
    +   "o 0.00",
      ]

      141 |     it('should return the sum of balances per network, using their symbols, sorted by quantity descently', () => {
      142 |       wrapper = mountPage()
    > 143 |       expect(wrapper.vm.totalBalances).toEqual([
          |                                        ^
      144 |         'm\xa0500.150909',
      145 |         'd\xa00.5201',
      146 |         'o\xa00.1219'

      at Object.toEqual (__tests__/unit/pages/Profile/ProfileAll.spec.js:143:40)
```

any idea how 225a404cc3c25f6f8a7f093c33c83faf97b5520c might be causing the rounding issue when run through github actions @faustbrian @alexbarnsley?

**Comment by alexbarnsley** [comment]
I think there's a problem with pagination 🤔 I can't seem to get past page 2, but the pagination buttons don't seem to change (e.g. it thinks it's still on page 1)

**Comment by dated** [comment]
Let me check, any specific table or all of em?

**Comment by dated** [comment]
Most likely, will fix ASAP..

**Comment by dated** [comment]
should be fixed now @alexbarnsley

**Comment by alexbarnsley** [comment]
thanks! I'll be back to checking on PRs in the next few days

**Pull request merged**
