### PR TITLE
refactor: fix alignment of menu dropdown components

### PR DESCRIPTION
**Pull request by dated**
## Summary

The position of the `MenuDropdown` components is currently changed by translating the element relative to its own position. This is error prone and exact alignment of multiple components becomes problematic, as can be see on the profile edition page:

image

With this PR the components are positioned relative to their parents and the prop type has been changed to be an object with the following base values. `x` or `y` can be ommitted when passing the prop.

```
position = {
  x: '0',
  y: '120%'
}
```

image

## Checklist

- [ ] Documentation _(if necessary)_
- [ ] Tests _(if necessary)_
- [x] Ready to be merged

### CODE REVIEW

**Comment by brenopolanski** [comment]
@dated I like your changes. Bbut I was thinking, perhaps a better solution would be to close the dropdown menu if there is a click outside the element. Like normal behavior of a native `<select />`. Make sense?

See how it looks opening all the dropdown menus:

Screenshot from 2020-03-04 14-12-04

**Comment by dated** [comment]
Yea, I'll fix that as well (it's like this on develop also)

**Comment by alexbarnsley** [comment]
Would you mind adding a test for the `adjustedPosition` computed property please

**Comment by dated** [comment]
> Would you mind adding a test for the `adjustedPosition` computed property please

done, cd5e3fb

**Comment by brenopolanski** [comment]
@dated have you done this: "close any sibling when opening a menu" ?

**Comment by dated** [comment]
Not yet, I'll remove the [WIP] as soon as I'm done.

**Comment by alexbarnsley** [comment]
Do the "close any sibling when opening a menu" in another PR. It's an existing issue not related to this

**Comment by dated** [comment]
Thanks @alexbarnsley, I'll open up an issue for it and finish my other stuff first before coming back to it.

**Pull request merged**
