### PR TITLE
fix: make it possible to input small numbers into the input field

### PR DESCRIPTION
**Pull request by ItsANameToo**
## Proposed changes

You couldn't input 0.0000001 as it would be turned into 1e-7:

schermafbeelding 2018-12-04 om 20 26 58

Now it's fixed and possible to input the correct amount:

schermafbeelding 2018-12-04 om 21 01 43

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)

## Checklist

- [x] I have read the [CONTRIBUTING](https://docs.ark.io/guidebook/contribution-guidelines/contributing.html) documentation
- [x] Lint and unit tests pass locally with my changes

### CODE REVIEW

**Comment by zillionn** [comment]
You could also restrict it to only positive numbers, because if balance is `0` and click `Send All` it shows `-txfee`.

**Comment by ItsANameToo** [comment]
Good point, will probably do that in a separate PR tho

**Comment by j-a-m-l** [comment]
Wouldn't it be better doing both things here? :thinking: To avoid checking the same thing 2 times

**Comment by ItsANameToo** [comment]
No, I get paid per PR for bounties and I don't think that change has to do with this PR as it would probably be a check on the switch and nothing to do with populating the value of the input field

**Pull request merged**
