### PR TITLE
fix: custom scrollbar on linux

### PR DESCRIPTION
**Pull request by luciorubeens**
## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)

### CODE REVIEW

**Comment by zillionn** [comment]
So no custom scrollbar on Mac?

**Comment by ItsANameToo** [comment]
@zillionn mac has a fancy scrollbar by itself:
schermafbeelding 2018-12-07 om 13 11 07

**Comment by zillionn** [comment]
Not my Mac 😢 

screenshot 2018-12-07 at 14 34 16

macOS Mojave
10.14.1 (18B75)

**Comment by ItsANameToo** [comment]
Interesting, I'm on Mojave too :thinking:

**Comment by alexbarnsley** [comment]
I'm still on High Sierra but have the same scrollbar as @zillionn

**Comment by alexbarnsley** [comment]
@ItsANameToo try a production version, see if you have the fancy scrollbar then

**Comment by zillionn** [comment]
> Interesting, I'm on Mojave too 

@ItsANameToo Maybe you're on something "stronger" than Mojave 😄

**Comment by zillionn** [comment]
Looks like it's a macOS setting...

screenshot 2018-12-07 at 14 48 32

**Comment by alexbarnsley** [comment]
@j-a-m-l 	@faustbrian 	would you mind testing this? I think you're both running Linux

**Comment by ItsANameToo** [comment]
I tried it on OSX and it looks as in the screenshot I posted above, so OSX is fine too

**Pull request merged**
