### PR TITLE
fix: check if wallets are synced with the network

### PR DESCRIPTION
**Pull request by goga-m**
## Summary
Prevents from erroring for unsynced wallets on `MyRegistrations` page 

Error : `This wallet has not been synchronized yet. Please call [syncIdentity] first`

## Checklist

- [ ] Documentation _(if necessary)_
- [x] Tests _(if necessary)_
- [x] Ready to be merged

### CODE REVIEW

**Comment by faustbrian** [comment]
Task linked: [CU-9ewzy9 REGISTRATIONS: This wallet has not been synchronized error](https://app.clickup.com/t/9ewzy9)

**Review by luciorubeens — COMMENTED** [review]
@goga-m It doesn't seem to solve the problem, I managed to reproduce it again.

**Comment by goga-m** [comment]
@luciorubeens there is an issue with ark cold wallets where even calling `syncIndentity` upon import, it needs some time until it will return 200 response from the network. Moved the check to `MyRegistrations` page to prevent from erroring, as we discussed, until we sort this out.

**Review by luciorubeens — APPROVED** [review]

**Comment by luciorubeens** [comment]
@goga-m Looks good now, just pushed a minor fix. Calling the `syncIdentity` manually is not necessary, as the SDK internally calls it in the `importByMnemonic` method.

**Pull request merged**
