### PR TITLE
refactor: separate logo in the sidebar

### PR DESCRIPTION
**Pull request by luciorubeens**
## Proposed changes

This PR separate the logo in the sidebar and also refactor to fix the overflow.

captura de tela 2018-12-07 as 15 20 13

49078221-30691800-f21c-11e8-87e1-9bc73e2d7325 copia

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [x] Refactoring (improve a current implementation without adding a new feature or fixing a bug)

### CODE REVIEW

**Comment by j-a-m-l** [comment]
@luciorubeens in your screenshot, the scrollbar is displayed. Is it on purpose?

**Comment by alexbarnsley** [comment]
@j-a-m-l i believe that's what Lucio has fixed

**Comment by zillionn** [comment]
This is the current situation with the left bar:
screenshot 2018-12-07 at 23 31 12

Lucio is making the icons to stay in the left bar and therefore scrollbar is needed or you won't be able to click them.

**Comment by alexbarnsley** [comment]
ah yes, makes sense. i hadn't actually tested it 👌

**Comment by j-a-m-l** [comment]
Thanks, that's what I though.

**Pull request merged**
