### PR TITLE
fix(styling): Add ButtonReload hover color

### LINKED ISSUE #874: Desktop Wallet no hover on refresh wallet creation
**Platform (please complete the following information):**
Windows 7

**Describe the bug**
The red arrows shows, the hover option does not work. The color stays the same when you move your mouse over that area.
**How to reproduce the bug**
Steps to reproduce the behaviour:
Create a new wallet

**Expected behaviour**
The color should change, showing the mouse is hovering over the refresh wallet address tab
desktop_wallet_no_hover

### PR DESCRIPTION
**Pull request by JeremiGendron**
Add conditional class, which is set through the hoverClass prop
and has a default of 'hover:bg-theme-option-button-hover'

Verified that it didn't apply to background-less ButtonReload

Fixes #874

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (improve a current implementation without adding a new feature or fixing a bug)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Build (changes that affect the build system)
- [ ] Docs (documentation only changes)
- [ ] Test (adding missing tests or fixing existing tests)
- [ ] Other... Please describe:

## Checklist

- [x] I have read the [CONTRIBUTING](https://docs.ark.io/guidebook/contribution-guidelines/contributing.html) documentation
- [x] Lint and unit tests pass locally with my changes (lint)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by JeremiGendron** [comment]
I'm not happy with the color, I'll change it. Do you have any suggestions?

**Comment by alexbarnsley** [comment]
@JeremiGendron could you provide a screenshot please. Best to ask Oleg regarding colours I think

**Comment by alexbarnsley** [comment]
Also, would you mind combining this with the password visibility PR #831 and the read more link PR #872 please. Just keep them as a generic UI/UX fixes PR

**Comment by JeremiGendron** [comment]
Sure thing. I'll try to keep everything central.

**Pull request closed without merging**
