### PR TITLE
feat: use websockets in plugins

### PR DESCRIPTION
**Pull request by alessiodf**
Allows plugins to connect to websockets if the `WEBSOCKETS` permission is granted. It sanitises event responses and also cleans up and disconnects the websockets when the navigation changes.
 
Reason for adding: Plugins can update with live data much easier using websockets than HTTP GET requests, especially due to the inability to access `setTimeout` and friends which makes periodically refreshing data over HTTP much harder. Websockets can push new data instead.

## What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Refactor
- [ ] Performance
- [ ] Tests
- [ ] Build
- [ ] Documentation
- [ ] Code style update
- [ ] Continuous Integration
- [ ] Other, please describe:

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Does this PR release a new version?

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `develop` branch, _not_ the `master` branch
- [ ] All tests are passing
- [ ] New/updated tests are included

If adding a **new feature**, the PR's description includes:

- [x] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

### CODE REVIEW

**Comment by alexbarnsley** [comment]
I know you've already deleted your repo so it's a pain. Would you mind adding some tests for `src/renderer/services/plugin-manager/websocket.js` please? Also, could I have an example of usage. A for me to test, but also to put into the docs. Thanks!

**Comment by alessiodf** [comment]
I haven't deleted the repo :suspi:

**Comment by alexbarnsley** [comment]
you told me you were going to remove it :colbert:

**Comment by alessiodf** [comment]
Going to != done it yet :sus:

**Comment by alessiodf** [comment]
I hope you like my tests @alexbarnsley xoxo

**Comment by alexbarnsley** [comment]
I can't see any of your tests

**Comment by alessiodf** [comment]
They got committed under your name for some reason 🤷‍♂️

**Pull request merged**
