### PR TITLE
fix: clear multiple recipient inputs upon addition

### PR DESCRIPTION
**Pull request by goga-m**
## Checklist

-   [x] My changes look good in both light AND dark mode
-   [x] The change is not hardcoded to a single network, but has multi-asset in mind
-   [x] I checked my changes for obvious issues, debug statements and commented code
-   [ ] Documentation _(if necessary)_
-   [x] Tests _(if necessary)_
-   [x] Ready to be merged

### CODE REVIEW

**Comment by faustbrian** [comment]
Task linked: [CU-c51f2p address input keeps old identicon upon clearing](https://app.clickup.com/t/c51f2p)

**Review by ItsANameToo — CHANGES_REQUESTED** [review]
it works, but looks like a test is hanging @goga-m

**Comment by goga-m** [comment]
Yeah, trying to reproduce it locally, will update and re-open PR when fixed.

**Comment by ItsANameToo** [comment]
still hangs @goga-m 🤔

**Comment by luciorubeens** [comment]
This [hook](https://github.com/ArkEcosystem/desktop-wallet/blob/3311193a8a690e88039fbd22d995c01ed59c5a27/src/domains/profile/components/SelectRecipient/SelectRecipient.tsx#L46-L50) is causing an infinite re-render.

**Comment by goga-m** [comment]
@luciorubeens @ItsANameToo that's right, although in UI seems fine, the infinite render is caused in some particular case in `AddParticipant.test.tsx`. Will troubleshoot it a bit further to come up with a fix

**Review by samharperpittam — APPROVED** [review]

**Review by ItsANameToo — APPROVED** [review]

**Pull request merged**
