### PR TITLE
fix: development mode message in production

### PR DESCRIPTION
**Pull request by luciorubeens**
Adding back #1095 

## What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Refactor
- [ ] Performance
- [ ] Tests
- [ ] Build
- [ ] Documentation
- [ ] Code style update
- [ ] Continuous Integration
- [ ] Other, please describe:

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Does this PR release a new version?

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `develop` branch, _not_ the `master` branch
- [x] All tests are passing
- [ ] New/updated tests are included

If adding a **new feature**, the PR's description includes:

- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

### CODE REVIEW

**Comment by alexbarnsley** [comment]
I just did a build from this branch and I'm still getting this message in devtools 🤔 
image

**Comment by faustbrian** [comment]
Shouldn't all the `build:*` commands be starting with `NODE_ENV=production` or Vue has no way of knowing that you are in production?

**Comment by alexbarnsley** [comment]
I don't think that's the case here. If it was running in development mode, plugins would need to be stored in a different folder (plugins-dev) which I would have expected someone to raise by now. I think this is a Vue message down to a specific configuration

**Comment by faustbrian** [comment]
Vue determines your environment based on `NODE_ENV`. If `NODE_ENV` isn't set to `production` you'll get message.

You can use `Vue.config.productionTip = true` to hide the message but that message doesn't even show up if you properly build for the `production` environment. That config value is generally only advised to be used if you are annoyed by the message in the console during development.

**Comment by dated** [comment]
https://github.com/ArkEcosystem/desktop-wallet/blob/develop/.electron-vue/build.js#L3

:thinking:

**Comment by alexbarnsley** [comment]
🤔 well spotted @dated. It's possibly due to the electron update, since we didn't have a problem in past releases

**Comment by luciorubeens** [comment]
@alexbarnsley Can you double check? It is definitely caused by `portal-vue`.

Our stack trace:
Captura de Tela 2019-08-30 às 07 38 40 cópia

I checked again and it's working.

**Comment by alexbarnsley** [comment]
🤔 	i will double check 👌

**Comment by alexbarnsley** [comment]
You are correct, it's working for me now. I don't know what I did locally, I even double-checked at the time when I was trying. Sorry for the waste of time!

**Pull request merged**
