### PR TITLE
fix: store server used to import as peer

### PR DESCRIPTION
**Pull request by luciorubeens**
Sets the server as a peer temporarily until it finds new peers.

## What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Refactor
- [ ] Performance
- [ ] Tests
- [ ] Build
- [ ] Documentation
- [ ] Code style update
- [ ] Continuous Integration
- [ ] Other, please describe:

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Does this PR release a new version?

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `develop` branch, _not_ the `master` branch
- [x] All tests are passing
- [ ] New/updated tests are included

If adding a **new feature**, the PR's description includes:

- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

### CODE REVIEW

**Comment by alexbarnsley** [comment]
I think it might be worth doing `SET_CURRENT_PEER` here too. I noticed that when I first created a profile for a new network, I wasn't connected to a peer until I refreshed 🤔

**Comment by faustbrian** [comment]
> I think it might be worth doing `SET_CURRENT_PEER` here too. I noticed that when I first created a profile for a new network, I wasn't connected to a peer until I refreshed 🤔

@luciorubeens

**Comment by ItsANameToo** [comment]
@luciorubeens needs changes :crazypuppyeyes:

**Comment by luciorubeens** [comment]
@alexbarnsley The peer was not being added to the list due to validation failure. Fixed by changing `delay` to `latency`.

**Comment by alexbarnsley** [comment]
👌 thanks, will take a look after the release

**Comment by faustbrian** [comment]
@alexbarnsley can this be reviewed and merged or does it need any changes?

**Comment by alexbarnsley** [comment]
@luciorubeens you didn't do `SET_CURRENT_PEER` 🤔

**Comment by alexbarnsley** [comment]
I mean, it loaded peers straight away so I'll merge

**Pull request merged**
