### PR TITLE
[WIP] feat: AIP-26 support

### PR DESCRIPTION
**Pull request by ItsANameToo**
## Proposed changes

TODO:
- [x] Basic URI handling
  - [x] message sign
  - [x] transfer
  - [x] vote
  - [x] delegate registration
  - [ ] ~add-network (postponed)~

---

- [ ] Error / success handling
  - [x] Show errors in case of invalid uri (e.g. missing required props)
  - [x] Show "already voted" message for wallets that already voted (+ look into unvote option)
  - [x] Show "already registered" message for wallets that are already a delegate
  - [ ] Navigate to wallet or show signed message content after successfully signing

---

- [ ] Tests
  - [x] Handle correct URIs
  - [ ] Handle incorrect URIs

---

- [x] Extra
  - [x] ~Look into the relay URI param (postponed)~
  - [x] Look into nethash URI param (the `select wallet` selection already does some checks to only show relevant wallets, so this might be enough)

## Types of changes

- [x] New feature (non-breaking change which adds functionality)

## Checklist

- [x] I have read the [CONTRIBUTING](https://docs.ark.io/guidebook/contribution-guidelines/contributing.html) documentation
- [x] Lint and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by ItsANameToo** [comment]
Maybe the both should learn about [WIP] 🤔

**Comment by ItsANameToo** [comment]
What's the status of this @ItsANameToo ?

**Comment by ItsANameToo** [comment]
It's nearly done; the URIs work but need to look into the "bad" cases where people have e.g. a malformed URI, and still need to look into fetching delegate information based on the network they are a delegate on

**Comment by alexbarnsley** [comment]
image

**Comment by alexbarnsley** [comment]
We're going to restart this after the 2.6 transaction types has been implemented (#1511)

**Pull request closed without merging**
