### PR TITLE
feat: add `MyRegistrations` delegate list

### PR DESCRIPTION
**Pull request by goga-m**
## Summary
Linked clickup task: https://app.clickup.com/t/9u5cmf

## Checklist

- [ ] Documentation _(if necessary)_
- [x] Tests _(if necessary)_
- [x] Ready to be merged

### CODE REVIEW

**Comment by goga-m** [comment]
Currently `wallet.client().delegate()` is used to get delegate info.
While this should be avoided, as wallet should not call `client` method directly, I am pasting here the list of all fields that are now displayed as placeholders in `DelegateRowItem` [component ](https://github.com/ArkEcosystem/desktop-wallet/pull/2717/files#diff-8778738684162cce5d15ff78195c1029) and need to be updated using the correct methods from sdk.

* MSQ 
* Status
* Forged Amount 
* Votes

@faustbrian whenever possible, could you update the correct methods (when available) that should be used to pull these data?

Thanks!

**Comment by faustbrian** [comment]
Will add them in the upcoming days but if the PR is otherwise functional @samharperpittam can test it so we can merge it.

**Comment by goga-m** [comment]
@faustbrian yes the functionality is there and should be working as expected. I'll update [clickup task](https://app.clickup.com/t/9u5cmf) with some additional notes and open the PR so we can merge this for now when @samharperpittam approves, and add adjustments in a following PR.

**Comment by samharperpittam** [comment]
Only thing remaining on this PR is the alignment of the Forged Amount column. Once fixed this PR can be merged.

**Review by samharperpittam — APPROVED** [review]

**Review by faustbrian — APPROVED** [review]

**Pull request merged**
