### PR TITLE
fix: include typegroup when setting last fee

### PR DESCRIPTION
**Pull request by dated**
## Summary

With this PR the last fees stored are grouped by type group, thus stopping magistrate transactions from overriding the last fees of standard transactions.

This PR also fixes the following Vuex error, which appears when sending a transaction:

```
vue.esm.js?a026:1897 Error: [vuex] do not mutate vuex store state outside mutation handlers.
    at assert (/Users/eddie/Documents/dev/Ark/desktop-wallet/node_modules/vuex/dist/vuex.common.js:92)
    at Vue.store._vm.$watch.deep (/Users/eddie/Documents/dev/Ark/desktop-wallet/node_modules/vuex/dist/vuex.common.js:776)
    at Watcher.run (vue.esm.js?a026:4571)
    at Watcher.update (vue.esm.js?a026:4545)
    at Dep.notify (vue.esm.js?a026:739)
    at Object.reactiveSetter (vue.esm.js?a026:1064)
    at Store.setLastFeeByType (session.js?5af3:434)
    at Array.wrappedActionHandler (/Users/eddie/Documents/dev/Ark/desktop-wallet/node_modules/vuex/dist/vuex.common.js:734)
    at Store.dispatch (/Users/eddie/Documents/dev/Ark/desktop-wallet/node_modules/vuex/dist/vuex.common.js:439)
    at Store.boundDispatch [as dispatch] (/Users/eddie/Documents/dev/Ark/desktop-wallet/node_modules/vuex/dist/vuex.common.js:333)
```

This PR refactors the respective action and mutation to get rid of the error.

**Important for testing:**

If you have tested #1755 and your apps last migration is set to 2.8.2 already, make sure to manually set it to a lower value so that this PRs migration gets applied.

For instance in `App.vue` add the following:

```
if (this.$store.getters['app/latestAppliedMigration'] === '2.8.2') {
  this.$store.dispatch('app/setLatestAppliedMigration', '2.8.1')
}
```

## Checklist

- [ ] Documentation _(if necessary)_
- [x] Tests _(if necessary)_
- [x] Ready to be merged

### CODE REVIEW

**Comment by brenopolanski** [comment]
@dated I can't reproduce this error.

Can you create a problem for that and add the steps to reproduce the error?

**Comment by dated** [comment]
I can reproduce it reliably by sending a regular transfer with a fee that is _not_ the last fee used 🤔

**Comment by dated** [comment]
If you can't reproduce the issue I'll repurpose this PR to something else: the `lastFees` state property doesn't differentiate between typegroups.

**Comment by dated** [comment]
> I'll repurpose this PR to something else: the `lastFees` state property doesn't differentiate between typegroups.

I added the respective changes, and added some information to this PRs description regarding testing.

**Pull request merged**
