### PR TITLE
feat: multipayment display modals details

### PR DESCRIPTION
**Pull request by dated**
## Summary

**TransactionShow**

 - aligns the smartbridge to the right and the label to top

**TransactionConfirmMultiPayment**

 - adds the recipient count
 - adds the total amount
 - adds the vendorfield and fee

**TransactionModal**

- limits the max height to `80vh`

image
image
image

## Checklist

- [ ] Documentation _(if necessary)_
- [ ] Tests _(if necessary)_
- [x] Ready to be merged

### CODE REVIEW

**Comment by davimello28** [comment]
Everything seems ok to me, but I have a scroll bar on the recipients under Debian 10 at 1366x768.  

image

On the third screen that you showed above, there is a very small part of the third transaction displayed. I think this can lead the user to ignore the third transaction if the scrollbar isn't displayed. I think that it would be better if you either aways display it or remove the clip at all.

**Comment by alexbarnsley** [comment]
All looks good, but we think the right-aligned vendorfield text looks a bit odd (I can see why you made it right-aligned, to match the other fields). I think one of the possible alternatives might be better:

- Revert to left-aligned
- Justify
- Move to the bottom (above payment list) and show it how it's shown on the confirmation screen:

image

**Comment by dated** [comment]
I'll see how it looks with justified alignment. Alignment to the left is a big no-go here imho, it breaks the design too much. Showing it underneath would be the better alternative, compared to left-alignment that is.

**Comment by dated** [comment]
I've went with `text-justify` for now @alexbarnsley.

**Pull request merged**
