### PR TITLE
feat: broadcast to multiple peers

### PR DESCRIPTION
**Pull request by ItsANameToo**
## Proposed changes

Enables switching between broadcasting to multiple peers or sending to just the connected peer (current behaviour)

## Types of changes

- [x] New feature (non-breaking change which adds functionality)

## Checklist

- [x] I have read the [CONTRIBUTING](https://docs.ark.io/guidebook/contribution-guidelines/contributing.html) documentation
- [x] Lint and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by zillionn** [comment]
It doesn't close the popup for me after I send the tx.

**Comment by ItsANameToo** [comment]
Yes, there were some changes on the develop branch that change the mechanic

**Comment by dated** [comment]
:hide:

**Comment by ItsANameToo** [comment]
always the same people :colbert:

**Comment by zillionn** [comment]
Did you integrate my changes here #841 ? I sent tx with `300` fee and got error message, even though the tx was broadcasted:

screenshot 2019-01-11 at 18 08 23

> {"data":{"accept":[],"broadcast":["72a83c813232f6fb0cd2638de32114a49000d19ecba3308f4504ef6519794680"],"excess":[],"invalid":["72a83c813232f6fb0cd2638de32114a49000d19ecba3308f4504ef6519794680"]},"errors":{"72a83c813232f6fb0cd2638de32114a49000d19ecba3308f4504ef6519794680":[{"type":"ERR_LOW_FEE","message":"Too low fee to be accepted in the pool"}]}}

**Comment by ItsANameToo** [comment]
@zillionn the aim of this PR was to add broadcasting to multiple peers. This does not include the changes you proposed in #841 as I believe that's not in the scope of this PR.

Why did you close your PR? I think it's a good addition, but it's not part of this PR 🤔

**Comment by zillionn** [comment]
I thought you're going to fix this and to be honest, I don't want to create PRs anymore.

However, with the latest `devnet` code, which doesn't return `invalid` and `error` anymore, your PR works fine and shows warning:

screenshot 2019-01-11 at 18 17 11

But it'll probably break on `mainnet`.

**Comment by ItsANameToo** [comment]
You can test a final time @alexbarnsley

**Pull request merged**
