### PR TITLE
feat: display transfer sender options when used through `ark:` protocol

### PR DESCRIPTION
**Pull request by alexbarnsley**
## Proposed changes

Dropdown on transfer form when using an `ark:` URI.

Todo:

- [x] Fix always loading URI on reload
- [x] Fix issue on "Next"
- [x] Fix sending whilst on a profile on a different network

## Types of changes

- [x] New feature (non-breaking change which adds functionality)

## Checklist

- [x] I have read the [CONTRIBUTING](https://docs.ark.io/guidebook/contribution-guidelines/contributing.html) documentation
- [x] Lint and unit tests pass locally with my changes

### CODE REVIEW

**Comment by zillionn** [comment]
If I select a `Mainnet` profile and click on a `Devnet` link
`ark:DT7quwHpfCCePpmhyf7MvyViCQ6KAVYr8c?amount=123&vendorField=test URI`
this popup appears and the fields a disabled:

screenshot 2018-12-21 at 13 00 25

**Comment by boldninja** [comment]
@zillionn new version with updated URI  UI is on the way.

**Comment by zillionn** [comment]
I'm testing `develop` branch with this merged PR.

**Comment by zillionn** [comment]
https://streamable.com/vjh0t

**Pull request merged**
