### PR TITLE
fix: update ModalQrCodeScanner component

### PR DESCRIPTION
**Pull request by dated**
Version [2.0.0](https://github.com/gruhn/vue-qrcode-reader/releases/tag/v2.0.0) of the `vue-qrcode-reader` package introduced some breaking changes, which went unnoticed. These caused the camera to not be able to be loaded anymore.

## What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Refactor
- [ ] Performance
- [ ] Tests
- [ ] Build
- [ ] Documentation
- [ ] Code style update
- [ ] Continuous Integration
- [ ] Other, please describe:

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Does this PR release a new version?

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `develop` branch, _not_ the `master` branch
- [x] All tests are passing
- [ ] New/updated tests are included

If adding a **new feature**, the PR's description includes:

- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

### CODE REVIEW

**Comment by alexbarnsley** [comment]
Possibly related to #1337? 🤔

**Comment by dated** [comment]
I'll try to reproduce that. With this issue however the camera wouldn't load at all.

**Comment by alexbarnsley** [comment]
No worries if it's not, Luka couldn't reproduce the issue @avfcpieface raised

**Comment by dated** [comment]
As mentioned in the issue itself, I think #1337 is a UX issue rather than anything functional.

**Pull request merged**
