### PR TITLE
fix(plugins): avatar plugin selection

### PR DESCRIPTION
**Pull request by alexbarnsley**
## Proposed changes

There were issues with the selection of plugin avatars. Originally it worked, because there was only one avatar to choose from. I've since added more to the plugin: https://github.com/alexbarnsley/desktop-wallet-avatar-plugin

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)

## Checklist

- [x] I have read the [CONTRIBUTING](https://docs.ark.io/guidebook/contribution-guidelines/contributing.html) documentation
- [x] Lint and unit tests pass locally with my changes

### CODE REVIEW

**Comment by alexbarnsley** [comment]
@j-a-m-l could you take a look at this please, as you've noticed avatar issues in the past. Thanks

**Comment by alexbarnsley** [comment]
thanks @j-a-m-l, i'll take a look

**Comment by alexbarnsley** [comment]
@j-a-m-l I just realised, that's correct functionality. The plugin won't be enabled for the newly created profile

**Comment by j-a-m-l** [comment]
@alexbarnsley why?

**Pull request merged**
