### PR TITLE
feat: load transaction from file

### PR DESCRIPTION
**Pull request by dated**
Allows the user to load a Transfer transaction from file (JSON). This populates the recipient, amount, fee and vendorfield fields.

## What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Refactor
- [ ] Performance
- [ ] Tests
- [ ] Build
- [ ] Documentation
- [ ] Code style update
- [ ] Continuous Integration
- [ ] Other, please describe:

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Does this PR release a new version?

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `develop` branch, _not_ the `master` branch
- [x] All tests are passing
- [ ] New/updated tests are included

If adding a **new feature**, the PR's description includes:

- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

### CODE REVIEW

**Comment by dated** [comment]
I could add some sanity checks to the data parsing before actually populating the form, such as verifying that the recipient is on the same network, or that the vendorfield isn't too long, but then again the form itself takes care of that anyway. What do you think @alexbarnsley?

**Comment by alexbarnsley** [comment]
🤔 I sort of think it might be worth it, at least to validate the address. That way, the user can be informed instead of them having to figure out why the address is invalid. I would say address validation is the only thing you would need, the rest it seems logical to use the form validation (not enough ARK, smartfield too long, etc)

**Comment by dated** [comment]
The recipient is now being validated before populating the form.

image

Other than the missing icon it's ready for review.

**Comment by alexbarnsley** [comment]
have you done the TODO @dated? 🤔 I can see your last commit but just confirming

**Comment by dated** [comment]
Yea, although I'm awaiting @olejegcord's final confirmation, I'll add `[WIP]` for the time being.

**Comment by dated** [comment]
All good :ok_hand:

**Comment by alexbarnsley** [comment]
Not tested just yet. Would you mind adding some tests (success and failure) for the `loadTransaction` method, please? You can probably just mock `electron_readFile` to return raw data. Thanks

**Pull request merged**
