### PR TITLE
feat: cache wallet page transactions

### PR DESCRIPTION
**Pull request by j-a-m-l**
This PR introduces a simplistic, but effective, way to cache transactions (resolves https://github.com/ArkEcosystem/desktop-wallet/issues/894).

## What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Refactor
- [ ] Performance
- [ ] Tests
- [ ] Build
- [ ] Documentation
- [ ] Code style update
- [ ] Continuous Integration
- [ ] Other, please describe:

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Does this PR release a new version?

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `develop` branch, _not_ the `master` branch
- [x] All tests are passing
- [ ] New/updated tests are included

If adding a **new feature**, the PR's description includes:

- [x] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

### CODE REVIEW

**Comment by j-a-m-l** [comment]
uhmm, @luciorubeens could you try to capture under which circumstances do you see that banner? I've never see it (it works well when I sen a transfer).

About storing only the last transactions and only store wallets / contacts, my idea was making navigation smoother, so users don't have to wait to navigate to / from pages that have been already visited. That specially useful under bad network conditions due user connection or due using a slow peer.

About the expiration date, what do you propose? flushing those old transactions at the beginning? checking the date every time that they are accessed?

**Comment by zillionn** [comment]
IMO you should cache all txs under one `key` (wallet address or public key) and use that cached object to show/order/paginate the txs. So if I go on the next page, you should check the cached object if it contains 50 txs older than oldest on the current page, otherwise query the API. You can use `/api/transactions/search` to retrieve 50 txs from timestamp < oldest tx on the current page.

And btw ordering of txs just doesn't work.

Screenshot 2019-06-02 at 18 52 15

Ordering by `Sender`, `Recipient` and `Smartbridge`:
Screenshot 2019-06-02 at 18 53 48

By `Date`:
page 1: 
Screenshot 2019-06-02 at 18 56 41
page 2:
Screenshot 2019-06-02 at 18 56 48

IMO you should only order the txs on the current page on the fly, same way the explorer is ordering them, without calling the API.

**Comment by j-a-m-l** [comment]
Thanks, @zillionn. I'll fix the ordering on this PR.

About sorting the transactions of the current page only, we can't do it because we'd lose a lot of functionality: for instance, users would need to navigate between lots of pages to see the first one, instead of just ordering them ascendantely. In the explorer that use cases are not as important.

And about aggregating transactions by address (instead of using the address, but the pagination too) the problems with that approach are:
 - when you visit an address with thousands of transactions, you've to download all of them to sort them
 - depending on the order parameter, you'd retrieve different sets of transactions, so you wouldn't be able to know how to sort them with other order parameters or which other not-yet-received transactions should be included

Keep in mind that this PR focus on making the navigation faster, not on having a copy of the entire data of an address. That could be a waste of space in several scenarios.

**Comment by zillionn** [comment]
I guess you don't understand me, do it as you decide.

**Comment by j-a-m-l** [comment]
I've re-read it and, @zillionn, your approach looks like a good one until you start thinking about edge cases, but if you think that the current implementation could be improved, I'd love to hear your feedback.

**Comment by dated** [comment]
i'd go so far as to say that remote sorting is the way to go, even on the explorer. i'll speak to @itsanametoo about it when i'm back.

**Comment by j-a-m-l** [comment]
Caching the last 50 would cover only 5 pages, so it could be useful, but it's limited.

About the refresh button, using the search endpoint to fetch only the latest could be a good optimization in some cases. Probably we could keep this PR approach and, later, dig into that other kind of enhancements.

**Comment by j-a-m-l** [comment]
The sorting problem is produced by core: https://github.com/ArkEcosystem/core/issues/2649

**Comment by ItsANameToo** [comment]
I get the same banner as @luciorubeens had when I:

1) Open a wallet
2) Go to `next` transaction screen
3) Go `back` to previous screen
4) Screen will now have that "10 new transactions" banner

Regarding the sorting, I think that remote sorting would be nice in the wallet as it is always limited to a specific address (unlike the explorer where you also have all transactions on the network as an option). Right now sorting is  all over the place as amounts work, but sender / receiver don't seem to work or at least not spanned over multiple pages of transactions. However, I think that's out of scope for this PR

**Comment by faustbrian** [comment]
@alexbarnsley what's the plan for this PR? Has been open for quite some time without any activity from the author.

**Comment by alexbarnsley** [comment]
I'll leave open for now and try to fix the issues raised when I get some free time

**Pull request closed without merging**
