### PR TITLE
feat: use last fee option

### LINKED ISSUE #1321: Proposal for a feature in the desktop wallet: fixed price for min payout
I would like to see a feature in the ark wallet that there is a possibility to set a fixed price for the min pay fee. This should just remember the latest entered min pay fee or making it possible to set one up in the settings menu.

Thank you Alex!

### PR DESCRIPTION
**Pull request by dated**
Implements and closes #1321.

## What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Refactor
- [ ] Performance
- [ ] Tests
- [ ] Build
- [ ] Documentation
- [ ] Code style update
- [ ] Continuous Integration
- [ ] Other, please describe:

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Does this PR release a new version?

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `develop` branch, _not_ the `master` branch
- [x] All tests are passing
- [ ] New/updated tests are included

If adding a **new feature**, the PR's description includes:

- [x] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

### CODE REVIEW

**Comment by alexbarnsley** [comment]
Getting these errors and no fee slider 🤔 

image

**Comment by alexbarnsley** [comment]
looks like `state.lastFees` isn’t defined, despite you setting it in `RESET` 🤔

**Comment by dated** [comment]
:hmhm: i thought i fixed that, will have a look in a bit

**Comment by alexbarnsley** [comment]
I think it's only when first running it. it's stopped now, I just keep getting an existing error which is intermittent (prior to your PR):

image

**Comment by alexbarnsley** [comment]
Whenever I try and look at that feeStatistics error it fixes itself 😂

**Comment by dated** [comment]
that's just the `uncertainty principle of dated's bugs` :trollface:

**Comment by alexbarnsley** [comment]
:susp:

**Pull request merged**
