### PR TITLE
fix: set tooltip container on transaction table

### PR DESCRIPTION
**Pull request by dated**
## Proposed changes

Partially solves #767 and replaces #822.

This sets the tooltip container to `.TransactionTable` and adds a property to `WalletAddress`, which allows to set a custom tooltip container.

tooltip

@j-a-m-l & @JeremiGendron can you confirm this works for you?

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [x] Refactoring (improve a current implementation without adding a new feature or fixing a bug)

## Checklist

- [x] I have read the [CONTRIBUTING](https://docs.ark.io/guidebook/contribution-guidelines/contributing.html) documentation
- [x] Lint and unit tests pass locally with my changes

### CODE REVIEW

**Comment by j-a-m-l** [comment]
This doesn't solve the problem, @dated. Thanks anyway for trying it.

**Comment by dated** [comment]
Which problem our we trying to solve? I am unable to replicate the issue described by Jeremi, but this solves the problem of the tooltip being shown above the app footer.

Imho adding an event listener to detect the scroll event and dismiss the tooltip is overkill.

**Comment by dated** [comment]
To clarify, this PR fixes this behaviour:

**Comment by zillionn** [comment]
Can't you listen for the scroll only when you show the tooltip and `onScroll` hide the tooltip and remove the listener?

**Comment by dated** [comment]
If anything such behaviour should be added to the Akryum/v-tooltip package.

**Comment by dated** [comment]
https://github.com/Akryum/v-tooltip/issues/145

**Comment by j-a-m-l** [comment]
@dated I missunderstood your intention: I though you were trying to fix that v-tooltip issue.

**Pull request merged**
