### PR TITLE
chore: stage linted files before commit

### PR DESCRIPTION
**Pull request by dated**
## Proposed changes

Adds the `git add` command to the lint-staged config, to include linted files in commits.

## Types of changes

- [x] Other... Please describe: config

## Checklist

- [x] I have read the [CONTRIBUTING](https://docs.ark.io/guidebook/contribution-guidelines/contributing.html) documentation
- [x] Lint and unit tests pass locally with my changes

### CODE REVIEW

**Comment by j-a-m-l** [comment]
@luciorubeens @alexbarnsley do you like the idea?

**Comment by dated** [comment]
The reason behind this is that it's very easy to push un-linted files with the current setup.

**Comment by j-a-m-l** [comment]
I understand, but maybe others, don't like the idea of pushing code that has been altered by a linter, without being reviewed: currently you have to accept manually the suggestions, so you are aware of the changes.

Since this change would affect the workflow of all the devs, asking to the rest of maintainers is a must.

**Comment by dated** [comment]
> Since this change would affect the workflow of all the devs, asking to the rest of maintainers is a must.

Sure! Just wanted to explain myself :D the `core` repository uses the setup proposed here, but it's a matter of personal preference in the end.

**Pull request merged**
