### PR TITLE
chore(deps): update all electron dependencies

### PR DESCRIPTION
**Pull request by faustbrian**
Update all `electron-*` dependencies.

## What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Refactor
- [ ] Performance
- [ ] Tests
- [x] Build
- [ ] Documentation
- [ ] Code style update
- [ ] Continuous Integration
- [ ] Other, please describe:

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Does this PR release a new version?

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `develop` branch, _not_ the `master` branch
- [x] All tests are passing
- [ ] New/updated tests are included

If adding a **new feature**, the PR's description includes:

- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

### CODE REVIEW

**Comment by alexbarnsley** [comment]
Seems to hang my wallet on my macbook pro 🤔

**Comment by ItsANameToo** [comment]
Doesn't hang for me :suspi:

**Comment by alexbarnsley** [comment]
Same since resetting data. @luciorubeens 	could you test to see if it still hangs for you, I don't want to just merge still as it could be the case that wallets with more profiles/wallets/other stuff start hanging. I was thinking it may be possible that the wallet storage starts to slow the app down the larger the size, since my app used to lag regardless of wallet

**Comment by luciorubeens** [comment]
Sounds good to me, I tested deeply with multiple wallets/profiles and it seems to hang for a few seconds when booting. I don't think it's related to Electron, probably it must be some synchronous task running on the main thread.

**Comment by alexbarnsley** [comment]
Let's get this moving then 👌

**Pull request merged**
