### PR TITLE
Fix/tabindex ci test

### PR DESCRIPTION
**Pull request by JeremiGendron**
#968 and https://github.com/ArkEcosystem/desktop-wallet/pull/933

### CODE REVIEW

**Comment by JeremiGendron** [comment]
seems tests are running now

**Comment by alexbarnsley** [comment]
Hi @JeremiGendron, would you mind going through the remaining forms to ensure the tabbing works correctly please? For example each transaction form with the fees. Thanks

**Comment by JeremiGendron** [comment]
@alexbarnsley sure thing

**Comment by j-a-m-l** [comment]
@JeremiGendron if you are interested in adding proper tabbing to the forms, the bounty would be changed. If not, in some days, I'd review this PR and merge or close it.

**Comment by j-a-m-l** [comment]
@JeremiGendron I'm going to close this PR due inactivity (some things are not correct yet)

**Pull request closed without merging**
